oidc:
  enabled: true
  id: ""
  redirect_uris: []
    # - https://example.com/path
  secret_name: "" # name of secret to be created, defaults to 'oidc-client.<CLIENT_ID>'

saml:
  enabled: false
  id: ""
  root_url: ""
  cert_domain: ""
  assertion_consumer:
    method: "post" # "redirect" or "post"
    url: "" # may be relative
  logout_service:
    method: "post" # "redirect" or "post"
    url: "" # may be relative
  secret_name: "" # name of secret to be created, defaults to 'saml-client.<CLIENT_ID>'

keycloak:
  local_url: http://keycloak.sso-system.svc.cluster.local
  subdomain: id
  realm: master
  user: admin
  password_secret:
    name: idp-admin
    namespace: sso-system
    key: admin-password
