{{- $pgPassword := get ((lookup "v1" "Secret" .Release.Namespace .Values.postgres.passwordSecret.name).data) .Values.postgres.passwordSecret.key | b64dec }}
{{- $rdPassword := get ((lookup "v1" "Secret" .Release.Namespace .Values.redis.passwordSecret.name).data) .Values.redis.passwordSecret.key | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.targetSecret.name }}
type: Opaque
data:
  {{ .Values.targetSecret.keys.postgres }}: {{ printf "pg://%s:5432?u=%s&p=%s&d=%s" .Values.postgres.serviceName .Values.postgres.user $pgPassword .Values.postgres.database | b64enc }}
  {{ .Values.targetSecret.keys.redis }}: {{ printf "redis://:%s@%s:6380" $rdPassword .Values.redis.serviceName | b64enc }}
