apiVersion: v1
kind: Secret
metadata:
  name: dns-token
type: Opaque
data:
  {{- $secretRef := .Values.token_secret }}
  digitalocean_api_token: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data) $secretRef.key }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "^6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    domainFilters:
      - {{ .Values.domain }}
    sources:
      - service
      - ingress
    txtOwnerId: {{ printf "%s.%s" .Values.cluster_name .Values.domain | quote }}
    provider: digitalocean
    digitalocean:
      secretName: dns-token
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
