{{- if not .Values.vcluster }}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k3s-auto-upgrade-plan
spec:
  dependsOn:
    - name: system-upgrade-controller
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: base-repo
    namespace: flux-system
  path: "./manifests/k3s-auto-upgrade-plan"
  prune: true
{{- end }}
