{{- if not .Values.vcluster }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
spec:
  interval: 1h
  url: https://github.com/rancher/system-upgrade-controller/
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  path: "./manifests"
  prune: true
{{- end }}
