{{- if not .Values.vcluster }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k3s-auto-upgrade-plan
spec:
  dependsOn:
    - name: system-upgrade-controller
  interval: 1h
  chart:
    spec:
      chart: k3s-auto-upgrade-plan
      version: "^0.1.0"
      sourceRef:
        kind: HelmRepository
        name: base-repo
        namespace: flux-system
  values:
    k3s_version: {{ .Values.k3s_version | default "null" }}
{{- end }}
