# Default values, copy to ./<CLUSTER_NAME>.config.yaml before making changes.
# Do not forget to also copy and fill out ./secrets.yaml!

domain: ""
org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logo_url: ""

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  from_address: ""
  # Put the password in ./<CLUSTER_NAME>.secrets.yaml

s3:
  endpoint: "" # Domain without protocol of your S3 endpoint (e.g. "s3.example.org")
  region: "eu-central-1" # Required by Longhorn, just leave the default if you don't have zones
  access_key_id: "" # Your S3 access key id
  # Put the access key secret in ./<CLUSTER_NAME>.secrets.yaml
s3_buckets:
  backup: ""
  logs: ""

admin_email: ""

vcluster: false # Set to true to create a vcluster on top of a k3s host cluster

restore_from_backup: null

subdomains:
  keycloak: "id"
  oauth2_proxy: "oauth"
  cluster: "k8s"
  dashboard: "dashboard.k8s"
  weave_gitops: "gitops.k8s"
  grafana: "grafana.k8s"
  longhorn: "longhorn.k8s"

auto_trust_remotes: false
clear_known_hosts: false

letsencrypt_staging: false # If true, uses Letsencrypt staging APIs instead of production ones. Prevents exceeding API limits.

base_repo: https://github.com/cloudlane-one/k8s-cloud
base_branch: main

ansible_user: root
