- name: Perform localhost setup steps, if according flags are set
  hosts: localhost
  connection: local
  roles:
    - role: clear-known-hosts
      when: "(clear_known_hosts is defined) and clear_known_hosts and (clear_known_hosts != 'false')"
    - role: auto-trust
      when: "(auto_trust_remotes is defined) and auto_trust_remotes and (auto_trust_remotes != 'false')"

- name: Run setup for all nodes
  hosts: all
  become: true
  roles:
    - role: node
  tasks:
    - name: Add host to control_nodes group, if flag is set
      when: "control_node"
      ansible.builtin.add_host:
        name: "{{ ansible_host }}"
        groups: control_nodes

- name: Setup infrastructure via kubectl from one of the control hosts
  hosts: control_nodes
  run_once: true
  become: true
  roles:
    - role: infrastructure
