- name: Perform localhost setup steps, if according flags are set
  hosts: localhost
  connection: local
  roles:
    - role: clear-known-hosts
      when: "(clear_known_hosts is defined) and clear_known_hosts and (clear_known_hosts != 'false')"
    - role: auto-trust
      when: "(auto_trust_remotes is defined) and auto_trust_remotes and (auto_trust_remotes != 'false')"

- name: Run setup for all nodes
  hosts: all
  become: true
  vars:
    control_nodes: "{{ groups['control_nodes'] | default([]) }}"
  roles:
    - role: node
  tasks:
    - name: Add first host to control_nodes group, if group wasn't explicitly created
      when: "'control_nodes' not in groups and inventory_hostname == groups['all'][0]"
      ansible.builtin.add_host:
        name: "{{ inventory_hostname }}"
        groups: control_nodes

- name: Setup infrastructure via kubectl from one of the control hosts
  tags: infra
  hosts: control_nodes
  run_once: true
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - role: infrastructure
