- name: Perform localhost setup steps, if according flags are set
  hosts: localhost
  connection: local
  roles:
    - role: clear-known-hosts
      when: "(clearKnownHosts is defined) and clearKnownHosts and (clearKnownHosts != 'false')"
    - role: auto-trust
      when: "autoTrustRemotes == true"

- name: Run setup for all nodes
  hosts: all
  become: true
  roles:
    - role: node-setup
      vars:
        main_control_host: "{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}"
        control_plane: "{{ 'control_plane' in group_names }}"

- name: Run setup for all control nodes
  hosts: control_plane
  become: true
  roles:
    - role: control-node-setup

- name: Setup infrastructure
  hosts: control_plane
  run_once: true
  become: true
  roles:
    - role: infra-setup
      environment:
        K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
