- name: Add all hosts to known_hosts file, if according flag is set
  hosts: localhost
  connection: local
  tags: cluster
  when: "autoTrustRemotes == true"
  roles:
    - auto-trust

- name: Run common setup for all nodes
  hosts: cluster
  become: true
  tags: cluster
  roles:
    - node-setup

- name: Run setup specific to control nodes
  hosts: cluster
  when: "{{ control_plane }}"
  become: true
  tags: cluster
  roles:
    - node-setup

- name: Set up cluster infrastructure
  hosts: cluster
  when: "{{ control_plane }}"
  run_once: true
  tags: infra
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - infra-setup
