apiVersion: v2
name: vcluster
description: HA vcluster with extras
type: application
version: "0.2.1"
appVersion: "0.19.1"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
