apiVersion: v2
name: cicd-stack
description: FluxCD + Weave-Gitops Dashboard + extras
type: application
version: "0.0.1"
appVersion: "0.0.1"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
