apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/rancher/system-upgrade-controller/
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: kube-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
    namespace: flux-system
  path: "./manifests"
  prune: true
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
