{{- if not .Values.vcluster }}
# This VolumeSnapshotClass will be used by Velero to automatically 
# trigger volume snapshotting and snapshot backup via Longhorn.
# See here: https://longhorn.io/docs/1.4.1/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup/#create-a-csi-volumesnapshot-associated-with-longhorn-backup
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  labels:
      velero.io/csi-volumesnapshot-class: "true"
  name: velero-backup
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: s3
type: Opaque
data:
  {{- $secretRef := .Values.s3.access_key_secret }}
  {{- $s3_secret := get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data) $secretRef.key | b64dec }}
  cloud: {{ printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s" .Values.s3.access_key_id $s3_secret | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: "^5.1.5"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  values:
    resources:
      requests:
        memory: 256Mi # measured on 2023-11-30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec: {{ .Files.Get "config/alert-rules.yaml" | nindent 10 }}
    upgradeCRDs: true
    credentials:
      useSecret: true
      existingSecret: s3
    configuration:
      features: EnableCSI
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: {{ .Values.s3.bucket }}
          prefix: velero
          config:
            region: {{ .Values.s3.region }}
            s3Url: {{ .Values.s3.endpoint }}
            serverSideEncryption: AES256
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: {{ .Values.s3.region }}
    initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    schedules:
      cluster-backup:
        disabled: false
        schedule: "0 0 * * *"
        useOwnerReferencesInBackup: false
        template:
          includedNamespaces:
            - "*"
          includeClusterResources: true
          snapshotVolumes: true
          storageLocation: default
          ttl: "168h"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob "config/grafana-dashboards/velero*").AsConfig | indent 2 }}
