- name: Determine host groups
  tags: infra
  hosts: localhost
  connection: local
  tasks:
    - name: Retrieve given host roles
      ansible.builtin.set_fact:
        backbone_hosts: "{{ hostvars | dict2items | selectattr('value.backbone', 'defined') | selectattr('value.backbone') | map(attribute='key') }}"
        control_hosts: "{{ hostvars | dict2items | selectattr('value.control', 'defined') | selectattr('value.control') | map(attribute='key') }}"

    - name: Set host roles to default, if not customized
      vars:
        tru_bb_nodes: "{{ hostvars | dict2items | selectattr('value.backbone', 'defined') | selectattr('value.backbone', '!=', false) | map(attribute='key') }}"
        default_backbone_hosts: "{{ hostvars | dict2items | selectattr('value.backbone', 'undefined') | map(attribute='key') | union(tru_bb_nodes) }}"
        first_backbone_node: "{{ backbone_hosts | default(default_backbone_hosts) | first }}"
      ansible.builtin.set_fact:
        control_hosts: "{{ control_hosts | default([first_backbone_node]) }}"

    - name: Add host to control_hosts group
      loop: "{{ control_hosts }}"
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: control_hosts

- name: Destroy all nodes
  hosts: all
  become: true
  vars:
    control: "{{ 'control_hosts' in group_names }}"
  roles:
    - role: destroy-node
      when: "not vcluster"
