apiVersion: v1
clusters:
- cluster:
    server: {{ api_url }}
  name: {{ cluster_name }}
contexts:
- context:
    cluster: {{ cluster_name }}
    user: {{ cluster_name }}
  name: {{ cluster_name }}
current-context: {{ cluster_name }}
kind: Config
preferences: {}
users:
- name: {{ cluster_name }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url={{ issuer_url }}
      - --oidc-client-id=cluster-oidc
      - --oidc-client-secret={{ client_secret }}
      command: kubectl
      env: null
      provideClusterInfo: false
