{{- if .Values.vcluster }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: "^3.11.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicas: 2
{{- end }}
