apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: piraeus
spec:
  interval: 1h
  url: https://piraeus.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-validation-webhook
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-validation-webhook
      version: "~1.7"
      sourceRef:
        kind: HelmRepository
        name: piraeus
{{- if not .Values.vcluster }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-controller
      version: "~1.8"
      sourceRef:
        kind: HelmRepository
        name: piraeus
  dependsOn:
    - name: snapshot-validation-webhook
{{- end }}
