{{- if not .Values.vcluster }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-snapshot-class
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/default-snapshot-class
      sourceRef:
        kind: GitRepository
        name: base-repo
        namespace: flux-system
      reconcileStrategy: Revision
  dependsOn:
    - name: snapshot-controller
{{- end }}
