{{- range $name, $replicas := (dict "single" 1 "double" 2 "triple" 3) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $name }}
  {{- if and (not $.Values.encrypt_default) (eq $replicas $.Values.default_replicas) }}
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
  {{- end }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  nodeSelector: {{ $.Values.cluster_name }}
  numberOfReplicas: {{ $replicas | quote }}
  dataLocality: best-effort
  staleReplicaTimeout: "2880" # 48 hours in minutes
---
{{- $name_enc := printf "%s-enc" $name }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $name_enc }}
  {{- if and $.Values.encrypt_default (eq $replicas $.Values.default_replicas) }}
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
  {{- end }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  nodeSelector: {{ $.Values.cluster_name }}
  numberOfReplicas: {{ $replicas | quote }}
  dataLocality: best-effort
  staleReplicaTimeout: "2880" # 48 hours in minutes
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: longhorn-encryption
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-publish-secret-name: longhorn-encryption
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-encryption
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
{{- end }}
---
{{- if not .Values.vcluster }}
# VCluster storage classes are synced to host, where they reference the
# already existing storage secret.
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-encryption
  namespace: longhorn-system
data:
  CRYPTO_KEY_VALUE: {{ include "common.secrets.passwords.manage" (dict "secret" "longhorn-encryption" "key" "CRYPTO_KEY_VALUE" "providedValues" (list "") "length" 16 "context" $) }}
  CRYPTO_KEY_PROVIDER: {{ "secret" | b64enc }}
  CRYPTO_KEY_CIPHER: {{ "aes-xts-plain64" | b64enc }}
  CRYPTO_KEY_HASH: {{ "sha256" | b64enc }}
  CRYPTO_KEY_SIZE: {{ "256" | b64enc }}
  CRYPTO_PBKDF: {{ "argon2i" | b64enc }}
{{- end }}
