- name: Chart details
  ansible.builtin.debug:
    msg: "Deploying chart {{ chart.name }} into namespace {{ chart.namespace }}"

- name: Get current kubectl context
  ansible.builtin.command: "kubectl config current-context"
  changed_when: false
  register: current_ctx

- name: Ensure chart namespace exists
  environment:
    K8S_AUTH_CONTEXT: "{{ kube_context | default(current_ctx.stdout) }}"
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ chart.namespace }}"

- name: Ensure HelmRelease for chart exists
  environment:
    K8S_AUTH_CONTEXT: "{{ kube_context | default(current_ctx.stdout) }}"
  kubernetes.core.k8s:
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: "{{ chart.name }}"
        namespace: "{{ chart.namespace }}"
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/{{ chart.name }}"
            sourceRef:
              kind: GitRepository
              name: base-repo
              namespace: flux-system
            reconcileStrategy: Revision
        values: "{{ chart.chart_values | default({}) | combine({'bootstrap': false}) }}"

- name: Reconcile HelmRelease
  vars:
    context: "{{ kube_context | default('') }}"
    context_arg: "{{ context | ternary('--context=' + context, '') }}"
  ansible.builtin.command:
    argv:
      - flux
      - reconcile
      - hr
      - "{{ chart.name }}"
      - "-n={{ chart.namespace }}"
      - "{{ context_arg }}"
  changed_when: true
