- name: Chart details
  ansible.builtin.debug:
    msg: "Deploying chart {{ chart['name'] }} into namespace {{ chart['namespace'] }}"

- name: Ensure chart namespace exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ chart['namespace'] }}"

- name: Ensure chart namespace is isolated via network policy
  when: "chart['namespace'] != 'kube-system'"
  kubernetes.core.k8s:
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: namespace-isolation
        namespace: "{{ chart['namespace'] }}"
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/namespace-isolation"
            sourceRef:
              kind: GitRepository
              name: base-repo
              namespace: flux-system
            reconcileStrategy: Revision

- name: Ensure HelmRelease for chart exists
  kubernetes.core.k8s:
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: "{{ chart['name'] }}"
        namespace: "{{ chart['namespace'] }}"
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/{{ chart['name'] }}"
            sourceRef:
              kind: GitRepository
              name: base-repo
              namespace: flux-system
            reconcileStrategy: Revision
        values: "{{ chart['values'] | combine({'bootstrap': false}) }}"

- name: Reconcile HelmRelease
  ansible.builtin.command: "flux reconcile hr {{ chart['name'] }} -n {{ chart['namespace'] }}"
  changed_when: true
