- name: Chart details
  ansible.builtin.debug:
    msg: "Deploying chart {{ chart.name }} into namespace {{ chart.namespace }}"

- name: Ensure chart namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ chart.namespace }}"

- name: Ensure HelmRelease for chart exists
  vars:
    default_vars:
      bootstrap: false
      vcluster: "{{ vcluster }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: "{{ chart.name }}"
        namespace: "{{ chart.namespace }}"
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/{{ chart.name }}"
            sourceRef:
              kind: GitRepository
              name: base-repo
              namespace: flux-system
            reconcileStrategy: Revision
        values: "{{ chart.chart_values | default({}) | combine(default_vars) }}"

- name: Reconcile HelmRelease
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ansible.builtin.command:
    argv:
      - flux
      - reconcile
      - hr
      - "{{ chart.name }}"
      - "-n={{ chart.namespace }}"
  changed_when: true

- name: Wait for component to become ready
  when: "'wait_on' in chart"
  loop: "chart.wait_on"
  kubernetes.core.k8s_info:
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    wait: true
    wait_timeout: 600
