- name: Set dynamic facts
  ansible.builtin.set_fact:
    cluster_fqn: "{{ subdomains.cluster }}.{{ domain }}"
    charts_dir: "{{ playbook_dir }}/charts"

- name: Get all k8s nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
  register: all_k8s_nodes

- name: Filter out nodes as per inventory
  ansible.builtin.set_fact:
    inventory_nodes: "{{ all_k8s_nodes.resources | json_query(node_filter) | json_query(node_extractor) }}"
  vars:
    node_filter: '[?contains({{ groups["all"] }}, metadata.annotations."k3s.io/external-ip")]'
    node_extractor: '[].metadata.annotations."k3s.io/hostname"'

- name: Add cluster FQN as label to all inventory nodes
  kubernetes.core.k8s:
    state: patched
    kind: Node
    name: "{{ item }}"
    definition:
      metadata:
        labels: "{{ {cluster_fqn: '1'} }}"
  loop: "{{ inventory_nodes }}"

- name: Ensure FluxCD is deployed
  kubernetes.core.helm:
    wait: true
    timeout: 10m
    name: fluxcd
    release_namespace: flux-system
    create_namespace: true
    chart_repo_url: https://fluxcd-community.github.io/helm-charts
    chart_ref: flux2
    chart_version: "^2"
    values:
      policies:
        create: false

- name: Ensure base GitRepository exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: base-repo
        namespace: flux-system
      spec:
        interval: 1h
        url: "{{ base_repo }}"
        ref:
          branch: "{{ base_branch }}"

- name: Reconcile base git repo
  ansible.builtin.command: "flux reconcile source git base-repo -n flux-system"
  changed_when: true

- name: Bootstrap host-cluster infrastructure
  when: "not vcluster"
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
  loop:
    - name: storage-stack
      namespace: longhorn-system
    - name: cert-stack
      namespace: cert-system
    - name: ingress-stack
      namespace: ingress-system

- name: Add cluster FQN as label to all Longhorn nodes in inventory
  kubernetes.core.k8s:
    state: patched
    api_version: longhorn.io/v1beta2
    kind: Node
    namespace: longhorn-system
    name: "{{ item }}"
    definition:
      spec:
        tags:
          - "{{ cluster_fqn }}"
  loop: "{{ inventory_nodes }}"

- name: Set KUBECONFIG to host cluster
  ansible.builtin.set_fact:
    kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') }}"

- name: Setup vcluster
  when: "vcluster"
  block:
    - name: Create vcluster for domain
      kubernetes.core.helm:
        wait: true
        name: vcluster
        release_namespace: "{{ cluster_fqn }}"
        chart_repo_url: https://charts.loft.sh
        chart_ref: vcluster
        chart_version: "^0.15"
        values:
          sync:
            persistentvolumes:
              enabled: true
            storageclasses:
              enabled: true
            volumesnapshots:
              enabled: true
            nodes:
              enabled: true
              enableScheduler: true
              nodeSelector: "{{ cluster_fqn }}=1"
            ingresses:
              enabled: true
            networkpolicies:
              enabled: true
          isolation:
            enabled: true
          proxy:
            metricsServer:
              nodes:
                enabled: true
              pods:
                enabled: true

    - name: Get vcluster KUBECONFIG
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ cluster_fqn }}"
        name: vc-vcluster
      register: virtual_kubeconfig

    - name: Save vcluster KUBECONFIG to file
      ansible.builtin.copy:
        content: "{{ virtual_kubeconfig.resources.data.config | b64decode }}"
        dest: /tmp/virtual-kubeconfig.yaml
        mode: '0644'

    - name: Set KUBECONFIG to vcluster
      ansible.builtin.set_fact:
        kubeconfig: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') }}"

- name: Bootstrap cluster infrastructure
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - name: telemetry-stack
      namespace: telemetry-system
    - name: cicd-stack
      namespace: flux-system

- name: Ensure all required secrets exist
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: kube-system
      type: Opaque
      data:
        secret: "{{ vars[item.inventoryKey] | b64encode }}"
  loop:
    - inventoryKey: smtp_password
      name: smtp
    - inventoryKey: s3_access_key_secret
      name: s3
    - inventoryKey: external_dns_token
      name: external-dns

- name: Ensure HelmReleases for host-cluster infrastructure exist
  when: "not vcluster"
  ansible.builtin.include_tasks:
    file: deploy-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - name: upgrade-controller
      namespace: kube-system

    - name: namespace-isolation
      namespace: longhorn-system

    - name: storage-stack
      namespace: longhorn-system
      chart_values:
        host: "{{ subdomains.storage }}.{{ domain }}"
        oauth2_proxy_host: "{{ subdomains.auth }}.{{ domain }}"
        admin_group: "cluster-admins"
        s3: "{{ s3 | combine({'access_key_secret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3_buckets.backup}) }}"

    - name: namespace-isolation
      namespace: cert-system

    - name: cert-stack
      namespace: cert-system

    - name: namespace-isolation
      namespace: ingress-system

    - name: ingress-stack
      namespace: ingress-system
      chart_values:
        letsencrypt_staging: "{{ letsencrypt_staging }}"

    - name: namespace-isolation
      namespace: backup-system

    - name: backup-stack
      namespace: backup-system
      chart_values:
        s3: "{{ s3 | combine({'access_key_secret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3_buckets.backup}) }}"

- name: Apply backup restoration
  when: "restore_from_backup"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    definition:
      apiVersion: velero.io/v1
      kind: Restore
      metadata:
        name: initial-cluster-restore
        namespace: backup-system
      spec:
        backupName: "{{ restore_from_backup }}"

- name: Ensure HelmReleases for cluster infrastructure exist
  ansible.builtin.include_tasks:
    file: deploy-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - name: admin-rbac
      namespace: kube-system
      chart_values:
        admin_group: "cluster-admins"

    - name: crypto-storage
      namespace: longhorn-system
      chart_values:
        cluster_fqn: "{{ cluster_fqn }}"

    - name: namespace-isolation
      namespace: dns-system

    - name: dns-stack
      namespace: dns-system
      chart_values:
        external_dns:
          token_secret:
            namespace: kube-system
            name: external-dns
            key: secret

    - name: sso-stack
      namespace: sso-system
      chart_values:
        domain: "{{ domain }}"
        org: "{{ org }}"
        hosts:
          keycloak: "{{ subdomains.idp }}.{{ domain }}"
          authproxy: "{{ subdomains.auth }}.{{ domain }}"
        clients:
          oidc:
            - id: cluster-oidc
              redirect_uris:
                - "https://{{ subdomains.telemetry }}.{{ domain }}/login/generic_oauth"
                - "https://{{ subdomains.gitops }}.{{ domain }}/oauth2/callback"
                - "http://localhost:8000/"
        smtp: "{{ smtp | combine({'password_secret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"
        admin_group: "cluster-admins"
        admin_email: "{{ admin_email }}"
        letsencrypt_staging: "{{ letsencrypt_staging }}"

    - name: namespace-isolation
      namespace: telemetry-system

    - name: telemetry-stack
      namespace: telemetry-system
      chart_values:
        domain: "{{ domain }}"
        org: "{{ org }}"
        host: "{{ subdomains.telemetry }}.{{ domain }}"
        oidc_client:
          idp_url: "https://{{ subdomains.idp }}.{{ domain }}/realms/master"
          id: "cluster-oidc"
          secret:
            namespace: sso-system
            name: "oidc-client.cluster-oidc"
            key: secret
        admin_email: "{{ admin_email }}"
        admin_group: "cluster-admins"
        s3: "{{ s3 | combine({'access_key_secret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3_buckets.logs}) }}"
        smtp: "{{ smtp | combine({'password_secret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"
        node_endpoints: "{{ groups['all'] }}"
        letsencrypt_staging: "{{ letsencrypt_staging }}"

    - name: namespace-isolation
      namespace: flux-system

    - name: cicd-stack
      namespace: flux-system
      chart_values:
        host: "{{ subdomains.gitops }}.{{ domain }}"
        oidc_client:
          idp_url: "https://{{ subdomains.idp }}.{{ domain }}/realms/master"
          id: "cluster-oidc"
          secret:
            namespace: sso-system
            name: "oidc-client.cluster-oidc"
            key: secret
        letsencrypt_staging: "{{ letsencrypt_staging }}"

    - name: control-stack
      namespace: kube-system
      chart_values:
        host: "{{ subdomains.control }}.{{ domain }}"
        oauth2_proxy_host: "{{ subdomains.auth }}.{{ domain }}"
        admin_group: "cluster-admins"

- name: Expose k8s API via Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: k8s-api
        namespace: default
        annotations:
          external-dns.alpha.kubernetes.io/managed-by: cluster
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      spec:
        rules:
          - host: "{{ cluster_fqn }}"
            http:
              paths:
                - backend:
                    service:
                      name: kubernetes
                      port:
                        number: 443
                  path: /
                  pathType: ImplementationSpecific

- name: Copy default kubeconfig file
  ansible.builtin.copy:
    remote_src: true
    src: "{{ kubeconfig }}"
    dest: /tmp/kubeconfig.yaml
    mode: '0644'

- name: Change server address of copied kubeconfig to public cluster FQN
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - set-cluster
      - default
      - "--server=https://{{ cluster_fqn }}"
  environment:
    KUBECONFIG: /tmp/kubeconfig.yaml
  changed_when: true

- name: Download kubeconfig file
  ansible.builtin.fetch:
    src: /tmp/kubeconfig.yaml
    dest: "{{ playbook_dir }}/{{ cluster_fqn }}.yaml"
    flat: true
