apiVersion: v2
name: personal-finance
description: Firefly III with SSO and other components
type: application
version: "0.1.0"
appVersion: "0.1.0"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
