apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-mariadb
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb
      version: "12.2.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    auth:
      database: vcluster
      username: vcluster
      existingSecret: vcluster-mariadb
    primary:
      persistence:
        enabled: true
        size: 4Gi
      nodeSelector:
        {{ .Values.cluster_name }}: "1"
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "vcluster-mariadb-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: data-vcluster-mariadb-0
