apiVersion: v1
kind: Secret
metadata:
  name: vcluster-mariadb
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "vcluster-mariadb" "key" "mariadb-password" "providedValues" (list "") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "vcluster-mariadb" "key" "mariadb-root-password" "providedValues" (list "") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "vcluster-mariadb" "key" "mariadb-replication-password" "providedValues" (list "") "context" $) }}
