apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loft-sh
spec:
  interval: 1h
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-mariadb-endpoint
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/custom-template
      sourceRef:
        kind: GitRepository
        name: base-repo
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    template: |
      {{ .Files.Get "files/mariadb-endpoint.yaml" | nindent 6 }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster
spec:
  interval: 1h
  chart:
    spec:
      chart: vcluster
      version: "'^0.15.3 || 0.15.3-beta.0'" # Need this fix: https://github.com/loft-sh/vcluster/pull/1089
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  timeout: 15m0s # Increase timeout to be sure.
  values:
    storage:
      persistence: false # use external db.
    sync:
      nodes:
        enabled: true
        nodeSelector: "{{ .Values.cluster_name }}=1"
      persistentvolumes:
        enabled: true
      storageclasses:
        enabled: true
      volumesnapshots:
        enabled: true
      ingresses:
        enabled: true
      networkpolicies:
        enabled: true
    proxy:
      metricsServer:
        nodes:
          enabled: true
        pods:
          enabled: true
    hostpathMapper:
      enabled: true
    syncer:
      extraArgs:
        - "--tls-san={{ .Values.host }}"
    vcluster:
      extraArgs:
        - "--kube-apiserver-arg=oidc-issuer-url={{ .Values.oidc_client.idp_url }}"
        - "--kube-apiserver-arg=oidc-client-id={{ .Values.oidc_client.id }}"
        - "--kube-apiserver-arg=oidc-groups-claim=groups"
      env:
        - name: K3S_DATASTORE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: vcluster-mariadb-endpoint
              key: url
    plugin:
      cert-manager-plugin:
        image: ghcr.io/loft-sh/vcluster-plugins/cert-manager-plugin:0.3.0
        imagePullPolicy: IfNotPresent
        rbac:
          role:
            extraRules:
              - apiGroups: ["cert-manager.io"]
                resources: ["issuers", "certificates"]
                verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
          clusterRole:
            extraRules:
              - apiGroups: ["apiextensions.k8s.io"]
                resources: ["customresourcedefinitions"]
                verbs: ["get", "list", "watch"]
