apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loft-sh
spec:
  interval: 1h
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-mariadb-endpoint
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/vcluster-mariadb-endpoint
      sourceRef:
        kind: GitRepository
        name: base-repo
        namespace: flux-system
      reconcileStrategy: Revision
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster
spec:
  interval: 1h
  chart:
    spec:
      chart: vcluster
      version: "^0.15.5"
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  timeout: 10m0s
  dependsOn:
    - name: vcluster-mariadb
  values:
    enableHA: true
    replicas: 2
    podDisruptionBudget:
      enabled: true
    storage:
      persistence: false # use external db.
    sync:
      nodes:
        enabled: true
        nodeSelector: "{{ .Values.cluster_name }}=1"
      persistentvolumes:
        enabled: true
      storageclasses:
        enabled: true
      volumesnapshots:
        enabled: true
      networkpolicies:
        enabled: true
    syncer:
      extraArgs:
        - "--tls-san={{ .Values.host }}"
        - "--sync-labels=svccontroller.k3s.cattle.io/lbpool"
        - "--mount-physical-host-paths=true"
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
    vcluster:
      baseArgs:
        - server
        - --write-kubeconfig=/data/k3s-config/kube-config.yaml
        - --data-dir=/data
        - --disable=traefik,servicelb,local-storage,coredns
        - --disable-network-policy
        - --disable-agent
        - --disable-cloud-controller
        - --flannel-backend=none
      extraArgs:
        - "--kube-apiserver-arg=oidc-issuer-url={{ .Values.oidc_client.idp_url }}"
        - "--kube-apiserver-arg=oidc-client-id={{ .Values.oidc_client.id }}"
        - "--kube-apiserver-arg=oidc-groups-claim=groups"
      env:
        - name: K3S_DATASTORE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: vcluster-mariadb-endpoint
              key: url
      resources:
        requests:
          cpu: 200m
          memory: 1.2Gi
    coredns:
      replicas: 2
      resources:
        requests:
          cpu: 30m
          memory: 32Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vcluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vcluster
  minReplicas: 2
  maxReplicas: {{ .Values.max_replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65
