apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux-community
spec:
  interval: 1h
  url: https://fluxcd-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd
spec:
  chart:
    spec:
      chart: flux2
      version: "^2.12.2"
      sourceRef:
        kind: HelmRepository
        name: flux-community
  interval: 1h
  timeout: 15m0s
  values:
    policies:
      create: false
    imageAutomationController:
      resources:
        requests:
          cpu: 50m # measured on 2023-11-30
    imageReflectionController:
      resources:
        requests:
          cpu: 50m # measured on 2023-11-30
    kustomizeController:
      resources:
        requests:
          cpu: 50m # measured on 2023-11-30
    notificationController:
      resources:
        requests:
          cpu: 50m # measured on 2023-11-30
    helmController:
      resources:
        requests:
          memory: 128Mi # measured on 2023-11-30
    sourceController:
      resources:
        requests:
          memory: 384Mi # measured on 2023-11-30
{{- if not .Values.bootstrap }}
    prometheus:
      podMonitor:
        create: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: flux-cluster
spec:
  resyncPeriod: 30s
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  json: >
    {{ (.Files.Get "config/grafana-dashboards/flux-cluster.json") | nindent 4 }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: flux-control-plane
spec:
  resyncPeriod: 30s
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  json: >
    {{ (.Files.Get "config/grafana-dashboards/flux-control-plane.json") | nindent 4 }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: flux-logs
spec:
  resyncPeriod: 30s
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  json: >
    {{ (.Files.Get "config/grafana-dashboards/flux-logs.json") | nindent 4 }}
{{- end }}