- name: Check whether whether control nodes were given explicitly
  ansible.builtin.set_fact:
    control_nodes_given: "{{ control_nodes | length > 0 }}"

- name: Determine the main control host (first to join the cluster)
  ansible.builtin.set_fact:
    main_control_node: "{{ control_nodes_given | ternary(control_nodes[0], groups['all'][0]) }}"

- name: Check whether this host is supposed to be a control node
  ansible.builtin.set_fact:
    control_node: "{{ inventory_hostname in control_nodes or inventory_hostname == main_control_node }}"

- name: Uninstall k3s server
  when: "control_node"
  ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
  changed_when: true

- name: Uninstall k3s agent
  when: "not control_node"
  ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
  changed_when: true
