apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
spec:
  interval: 10m
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: '^0.14'
      sourceRef:
        kind: HelmRepository
        name: dex
  valuesFrom:
    - kind: Secret
      name: admin-oidc
      valuesKey: secret
      targetPath: "config.staticClients[0].secret"
  values:
    rbac:
      createClusterScoped: false
    envVars:
      - name: IDP_CLIENT_ID
        value: {{ .Values.admin_idp.client_id }}
      - name: IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: admin-idp-client
            key: secret
    config:
      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory
      issuer: {{ printf "https://%s" .Values.hosts.dex }}
      connectors:
        - type: {{ .Values.admin_idp.type }}
          id: {{ printf "admin_idp-%s" .Values.admin_idp.type }}
          name: {{ printf "admin_idp-%s" .Values.admin_idp.type }}
          config:
            # Credentials can be string literals or pulled from the environment.
            clientID: $IDP_CLIENT_ID
            clientSecret: $IDP_CLIENT_SECRET
            redirectURI: {{ printf "https://%s/callback" .Values.hosts.dex }}
            # flag which will switch from using the internal GitHub id to the users handle (@mention) as the user id.
            # It is possible for a user to change their own user name but it is very rare for them to do so
            {{ if eq .Values.admin_idp.type "github" -}}
            useLoginAsID: true
            loadAllGroups: true
            {{- else if eq .Values.admin_idp.type "oidc" -}}
            issuer_url: {{ .Values.admin_idp.issuer_url }}
            scopes:
              - profile
              - email
              - groups
            {{- end }}
      staticClients:
        - id: admin-oidc
          secret: "" # injected
          name: "Admin OIDC"
          redirectURIs:
            - {{ printf "https://%s/realms/main" .Values.hosts.keycloak }}
      oauth2:
        skipApprovalScreen: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.cluster_issuer }}
        external-dns.alpha.kubernetes.io/managed-by: {{ .Values.external_dns_manager }}
      hosts:
        - host: {{ .Values.hosts.dex }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - {{ .Values.hosts.dex }}
          secretName: dex-cert
