apiVersion: v1
kind: Secret
metadata:
  name: admin-oidc
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" "admin-oidc" "key" "secret" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: idp-cert
type: kubernetes.io/tls
data:
  {{- $idp_cert := dict "tls.crt" "" "tls.key" "" -}}

  {{- if not (include "common.secrets.exists" (dict "secret" "idp-cert" "context" $)) -}}
  {{- $gen_cert := genSelfSignedCert .Values.domain nil nil 3650 -}}
  {{- $_ := set $idp_cert "tls.crt" ($gen_cert.Cert | replace "\n" "" | trimPrefix "-----BEGIN CERTIFICATE-----" | trimSuffix "-----END CERTIFICATE-----" | b64enc) -}}
  {{- $_ := set $idp_cert "tls.key" ($gen_cert.Key | replace "\n" "" | trimPrefix "-----BEGIN RSA PRIVATE KEY-----" | trimSuffix "-----END RSA PRIVATE KEY-----" | b64enc) -}}
  {{- else -}}
  {{- $idp_cert = (lookup "v1" "Secret" .Release.Namespace "idp-cert").data -}}
  {{- end -}}

  tls.crt: {{ index $idp_cert "tls.crt" }}
  tls.key: {{ index $idp_cert "tls.key" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: idp-admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "idp-admin" "key" "password" "providedValues" (list "") "context" $) }}
---
{{- range $client := .Values.clients.oidc }}
apiVersion: v1
kind: Secret
metadata:
  {{- $client_secret := (printf "oidc-client.%s" $client.id) }}
  name: {{ $client_secret }}
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" $client_secret "key" "secret" "providedValues" (list "") "context" $) }}
---
{{- end }}
{{- range $client := .Values.clients.saml }}
apiVersion: v1
kind: Secret
metadata:
  {{- $client_secret := (printf "saml-cert.%s" $client.id) }}
  name: {{ $client_secret }}
type: kubernetes.io/tls
data:
  {{- $cert := dict "tls.crt" "" "tls.key" "" -}}

  {{- if not (include "common.secrets.exists" (dict "secret" $client_secret "context" $)) -}}
  {{- $gen_cert := genSelfSignedCert .Values.domain nil nil 3650 -}}
  {{- $_ := set $cert "tls.crt" ($gen_cert.Cert | replace "\n" "" | trimPrefix "-----BEGIN CERTIFICATE-----" | trimSuffix "-----END CERTIFICATE-----" | b64enc) -}}
  {{- $_ := set $cert "tls.key" ($gen_cert.Key | replace "\n" "" | trimPrefix "-----BEGIN RSA PRIVATE KEY-----" | trimSuffix "-----END RSA PRIVATE KEY-----" | b64enc) -}}
  {{- else -}}
  {{- $cert = (lookup "v1" "Secret" .Release.Namespace $client_secret).data -}}
  {{- end -}}

  tls.crt: {{ index $cert "tls.crt" }}
  tls.key: {{ index $cert "tls.key" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-creds
type: Opaque
data:
  {{- $passRef := .Values.smtp.passwordSecret }}
  password: {{ (lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data | get $passRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-idp-client
type: Opaque
data:
  {{- $secretRef := .Values.adminIDP.clientSecret }}
  secret: {{ (lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data | get $secretRef.key }}
---
{{- end }}