{{- if not .Values.bootstrap }}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
type: Opaque
data:
  issuerURL: {{ .Values.oidcClient.idpURL | b64enc }}
  clientID: {{ .Values.oidcClient.id | b64enc }}
  {{- $secretRef := .Values.oidcClient.secret }}
  clientSecret: {{ (lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data | index $secretRef.key }}
  redirectURL: {{ printf "https://%s/oauth2/callback" .Values.host | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h
  timeout: '30m0s' # Setting up public domains for OIDC takes time.
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
        external-dns.alpha.kubernetes.io/managed-by: {{ .Values.externalDNSManager }}
      hosts:
        - host: {{ .Values.host }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - {{ .Values.host }}
    metrics:
      enabled: false
{{- end }}
