{{- if and (not .Values.bootstrap) (not .Values.letsencrypt_staging) }}
# Disable weave-gitops entirely when letsencrypt_staging=true, as it offers no tls-skip-verify option.
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
type: Opaque
data:
  issuerURL: {{ .Values.oidc_client.idp_url | b64enc }}
  clientID: {{ .Values.oidc_client.id | b64enc }}
  {{- $secretRef := .Values.oidc_client.secret }}
  clientSecret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data) $secretRef.key }}
  redirectURL: {{ printf "https://%s/oauth2/callback" .Values.host | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h
  timeout: '30m0s' # Setting up public domains for OIDC takes time.
  values:
    adminUser:
      create: false
    additionalArgs:
      - --auth-methods=oidc
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: {{ .Values.host }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - {{ .Values.host }}
    metrics:
      enabled: false
    networkPolicy:
      create: false
{{- end }}
