apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: base-repo
spec:
  interval: 1h
  url: {{ .Values.base_repo }}
  ref:
    branch: {{ .Values.base_branch }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: letsencrypt-issuer
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/letsencrypt-issuer
      sourceRef:
        kind: GitRepository
        name: base-repo
      reconcileStrategy: Revision
  values:
    admin_email: {{ .Values.admin_email }}
