apiVersion: v2
name: admin-rbac
description: Setup RBAC for an admin group
type: application
version: "0.1.0"
appVersion: "0.1.0"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
