flannel-backend: "wireguard-native"
flannel-external-ip: True
disable:
  - traefik
  - local-storage
etcd-expose-metrics: true
secrets-encryption: true
kube-apiserver-arg:
  - "oidc-issuer-url=https://{{ subdomains.keycloak }}.{{ domain }}/realms/master"
  - "oidc-client-id=cluster-oidc"
  - "oidc-groups-claim=groups"
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
tls-san: "{{ subdomains.k8s_api }}.{{ domain }}"
kubelet-arg:
  - "kube-reserved=cpu=800m,memory=1600Mi,ephemeral-storage=2Gi"
  - "system-reserved=cpu=200m,memory=400Mi,ephemeral-storage=2Gi"
