{% if tailscale.enabled %}
{% if tailscale.headscale_url %}
vpn-auth: "name=tailscale,joinKey={{ tailscale_auth_key }},controlServerURL={{ tailscale.headscale_url }}"
{% else %}
vpn-auth: "name=tailscale,joinKey={{ tailscale_auth_key }}"
{% endif %}
{% else %}
node-external-ip: "{{ inventory_hostname }}"
{% endif %}
kubelet-arg:
  - "system-reserved=cpu=200m,memory=300Mi,ephemeral-storage=2Gi"
  - "eviction-hard=memory.available<100Mi,nodefs.available<5%"
  - "eviction-soft=memory.available<300Mi,nodefs.available<10%"
  - "eviction-soft-grace-period=memory.available=2m0s,nodefs.available=10m0s"
  - "eviction-max-pod-grace-period=180"
  - "node-ip=0.0.0.0"
