node-external-ip: "{{ inventory_hostname }}"
kubelet-arg:
  - "eviction-hard=memory.available<100Mi,nodefs.available<5%"
  - "eviction-soft=memory.available<400Mi,nodefs.available<10%"
  - "eviction-soft-grace-period=memory.available=2m0s,nodefs.available=10m0s"
  - "eviction-max-pod-grace-period=180"
