hosts:
  nextcloud: ""
  onlyoffice: ""

org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logo_url: ""
  default_phone_region: "" # ISO2 code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

oidc_client:
  idp_url: ""
  id: cluster-oidc
  secret:
    namespace: sso-system
    name: cluster-oidc
    key: secret

s3:
  enabled: true # Use S3 bucket as primary file storage.
  endpoint: "" # Hostname (without URL scheme) of your S3 endpoint
  region: "de"
  access_key_id: "" # Your S3 access key id
  access_key_secret:
    # Your S3 access key secret
    namespace: null
    name: nextcloud-s3
    key: access_key_secret
  bucket: "" # Name of bucket
  encryption:
    enabled: false
    existingSecret:
      enabled: false # Set to true to use existing key instead of generating one.
      namespace: null # Set to null to use current namespace
      name: ""
      key: key

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  password_secret:
    namespace: kube-system
    name: mail-smtp
    key: password
  from_address: ""

ingress: true

storage:
  size: 6Gi
  zone: "" # Enter zone name to localize storage to that zone.
  encrypted: false
  auto_backup: true
  local: false # Deploy as local, single-replica volume

snapshots:
  enabled: true
  class_name: snap

autoconfig:
  enabled: false

nginx:
  enabled: false # currently broken.

debug: false
