apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nimbolus
spec:
  interval: 1h
  url: https://nimbolus.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: system-upgrade-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: system-upgrade-controller
      version: "^0.3.0"
      sourceRef:
        kind: HelmRepository
        name: nimbolus
  values:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
