host: ""

org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logoURL: ""

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  password_secret:
    namespace: null
    name: ""
    key: "secret"
  from_address: ""

admin_email: ""

cluster_issuer: "acme"

external_dns_manager: "cluster"
