vcluster: false

s3:
  endpoint: "" # Full URL of your S3 endpoint (minus credentials)
  region: "de"
  access_key_id: "" # Your S3 access key id
  access_key_secret:
    # Your S3 access key secret
    namespace: kube-system
    name: backup-s3
    key: access_key_secret
  bucket: "" # Name of bucket
