{{- if not .Values.bootstrap }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-access-key
type: Opaque
data:
  {{- $secretRef := .Values.s3.access_key_secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data) $secretRef.key }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "^2"
      sourceRef:
        kind: HelmRepository
        name: grafana
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  valuesFrom:
    - kind: Secret
      name: s3-access-key
      valuesKey: secret
      targetPath: loki.config.storage_config.aws.secret_access_key
  values:
    loki:
      isDefault: false
      config:
        schema_config:
          configs:
          - from: "2023-06-05"
            store: boltdb-shipper
            object_store: s3
            schema: v11
            index:
              prefix: index_
              period: 24h
        ruler:
          storage:
            type: local
            local:
              directory: /tmp/rules
          rule_path: /tmp/scratch
          alertmanager_url: http://kube-prometheus-stack-alertmanager.o11y-system:9093
          ring:
            kvstore:
              store: inmemory
          enable_api: true
        storage_config:
          aws:
            # https://grafana.com/docs/loki/latest/configuration/#s3_storage_config
            s3: {{ printf "https://%s" .Values.s3.endpoint }}
            bucketnames: {{ .Values.s3.bucket }}
            endpoint: {{ .Values.s3.endpoint }}
            region: {{ .Values.s3.region }}
            access_key_id: {{ .Values.s3.access_key_id | quote }}
            # secret_access_key: "" # injected, see above
        limits_config:
          retention_period: 168h
{{- end }}
