apiVersion: v1
kind: Secret
metadata:
  name: loki-basicauth
type: Opaque
data:
  name: {{ "cluster" | b64enc }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "loki-basicauth" "key" "password" "providedValues" (list "") "length" 16 "context" $) }}
---
{{- if not .Values.bootstrap }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "^5.9.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  dependsOn:
    - name: minio
  valuesFrom:
    - kind: Secret
      name: minio-loki
      valuesKey: secret
      targetPath: loki.storage.s3.secretAccessKey
    - kind: Secret
      name: loki-basicauth
      valuesKey: password
      targetPath: gateway.basicAuth.password
  values:
    loki:
      configStorageType: Secret
      storage:
        type: s3
        s3:
          endpoint: http://minio:9000
          accessKeyId: loki
          # secretAccessKey: "" # injected, see above
          s3ForcePathStyle: true
          insecure: true
      compactor:
        retention_enabled: true
      limits_config:
        retention_period: 168h
      commonConfig:
        replication_factor: 1
    read:
      replicas: 1
      resources:
        requests:
          cpu: 30m
          memory: 128Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    write:
      replicas: 1
      resources:
        requests:
          cpu: 30m
          memory: 128Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    tableManager:
      resources:
        cpu: 50m
        memory: 64Mi
    backend:
      replicas: 1
      resources:
        requests:
          cpu: 30m
          memory: 64Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    gateway:
      basicAuth:
        enabled: true
        username: cluster
        # password: "" # injected, see above
      replicas: 1
      resources:
        requests:
          cpu: 250m
          memory: 32Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
{{- end }}
