apiVersion: v2
name: tandoor
description: Recipes + shopping lists + X
type: application
version: "0.1.5"
appVersion: "1.5.35"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
