apiVersion: v2
name: rocketchat
description: Rocket.Chat with SSO and some useful extras
type: application
version: "0.4.0"
appVersion: "6.13.0"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
