apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace-isolation
spec:
  egress:
    - {}
  ingress:
    - from:
        {{- range .Values.system_namespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
        {{- if gt (len .Values.ingress_whitelist) 0 }}
        {{- .Values.ingress_whitelist | toYaml | nindent 8 }}
        {{- end }}
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
