apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace-isolation
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
    {{- range .Values.namespace_whitelist }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
    {{- end }}
    {{- if gt (len .Values.selector_whitelist) 0 }}
    - from: {{- .Values.selector_whitelist | toYaml | nindent 8 }}
    {{- end }}
