apiVersion: v1
kind: Secret
metadata:
  name: admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "admin" "key" "password" "providedValues" (list "") "context" $) }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: frappe
spec:
  interval: 1h
  url: https://helm.erpnext.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erpnext
spec:
  interval: 1h
  chart:
    spec:
      chart: erpnext
      version: "^6"
      sourceRef:
        kind: HelmRepository
        name: frappe
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  valuesFrom:
    - kind: Secret
      name: admin
      valuesKey: password
      targetPath: "jobs.createSite.adminPassword"
  values:
    image: {{ .Values.image | toYaml | nindent 6 }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.cluster_issuer }}
        external-dns.alpha.kubernetes.io/managed-by: {{ .Values.external_dns_manager }}
      hosts:
      - host: {{ .Values.host }}
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: erpnext-tls
        hosts:
           - {{ .Values.host }}
    jobs:
      createSite:
        enabled: true
        siteName: {{ .Values.host }}
        # adminPassword injected via FluxCD
        installApps:
        - erpnext
        - payments
        - non_profit
    persistence:
      worker:
        enabled: true
        storageClass: {{ .Values.storage_class }} # TODO: PR to make this accept null for the default class
