apiVersion: v2
name: nextcloud
description: Nextcloud with SSO and some useful extras
type: application
version: "0.11.0"
appVersion: "29.0.1"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
