apiVersion: v2
name: nextcloud
description: Nextcloud with SSO and some useful extras
type: application
version: "0.9.2"
appVersion: "27.1.4"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
