apiVersion: v2
name: nextcloud
description: Nextcloud with SSO and some useful extras
type: application
version: "0.10.5"
appVersion: "28.0.4"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
