hosts:
  nextcloud: ""
  onlyoffice: ""

org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logo_url: ""
  default_phone_region: "" # ISO2 code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

s3:
  enabled: true # Use S3 bucket as primary file storage.
  endpoint: "" # Hostname (without URL scheme) of your S3 endpoint
  region: "de"
  access_key_id: "" # Your S3 access key id
  access_key_secret:
    # Your S3 access key secret
    namespace: null
    name: nextcloud-s3
    key: access_key_secret
  bucket: "" # Name of bucket
  encryption:
    enabled: false

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  password_secret:
    namespace: kube-system
    name: mail-smtp
    key: password
  from_address: ""

oidc:
  auto_redirect: true

ingress: true

storage:
  size: 6Gi
  encrypted: false
  auto_backup: true

zone: "" # Specific zone to localize this release to (pods and volumes)

snapshots:
  enabled: true
  class_name: snap

autoconfig:
  enabled: false

debug: false
