clients:
  oidc: []
  #    - id: ""
  #      redirectURIs:
  #        - https://example.com/path
  saml: []
  #    - id: ""
  #      rootURL: ""
  #      assertionConsumer:
  #        method: "post" # "redirect" or "post"
  #        url: "" # may be relative
  #      logoutService:
  #        method: "post" # "redirect" or "post"
  #        url: "" # may be relative

domain: ""

hosts:
  keycloak: ""
  dex: ""

smtp:
  host: ""
  port: ""
  from_address: ""
  username: ""
  starttls: false
  passwordSecret:
    namespace: null
    name: ""
    key: "password"

org:
  name: ""
  defaultLocale: "en_US"
  tagline: ""
  logoURL: ""

admin_idp:
  type: "oidc"
  issuer_url: ""
  client_id: ""
  clientSecret:
    namespace: null
    name: ""
    key: "secret"

admin_group: ""

clusterIssuer: "acme"

externalDNSManager: "cluster"
