cluster_client:
  id: cluster-oidc
  redirect_uris: []

clients:
  oidc: []
  #    - id: ""
  #      redirect_uris:
  #        - https://example.com/path
  saml: []
  #    - id: ""
  #      root_url: ""
  #      assertion_consumer:
  #        method: "post" # "redirect" or "post"
  #        url: "" # may be relative
  #      logout_service:
  #        method: "post" # "redirect" or "post"
  #        url: "" # may be relative

domain: ""

hosts:
  keycloak: ""
  authproxy: ""
  account_console: ""

smtp:
  host: ""
  port: ""
  user: ""
  from_address: ""
  starttls: false
  password_secret:
    namespace: kube-system
    name: mail-smtp
    key: password

org:
  name: ""
  default_locale: "en_US"
  tagline: ""
  logo_url: ""

admin_group: ""
admin_email: ""

snapshots:
  enabled: true
  class_name: snap

letsencrypt_staging: false

zone: "" # Specific zone to localize this release to (pods and volumes)

ha_deployment:
  enabled: false
  max_replicas: 4
