apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: oauth2-proxy
spec:
  interval: 10m
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client
type: Opaque
data:
  {{- $secretRef := .Values.oidc_client.secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef.namespace) $secretRef.name).data) $secretRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cookies
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" "cookies" "key" "secret" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: '^6'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  valuesFrom:
    - kind: Secret
      name: oidc-client
      valuesKey: secret
      targetPath: config.clientSecret
    - kind: Secret
      name: cookies
      valuesKey: secret
      targetPath: config.cookieSecret
  values:
    config:
      clientId: {{ .Values.oidc_client.id }}
      # clientSecret: "" # injected via valuesFrom
      # cookieSecret: "" # injected via valuesFrom
      configFile: |-
        upstreams = "file:///dev/null"
        whitelist_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        provider = "oidc"
        provider_display_name = {{ printf "SSO for %s" .Values.org.name | quote }}
        oidc_issuer_url = {{ .Values.oidc_client.idp_url | quote }}
        redirect_url = {{ printf "https://%s/callback" .Values.host | quote }} # TODO: insert correct url
        set_xauthrequest = true
        set_authorization_header = true
        pass_authorization_header = true
        pass_access_token = true
        cookie_samesite = "none"
        cookie_domains = [ {{ printf ".%s" .Values.domain | quote }} ]
        cookie_refresh = "300s"
        email_domains = "*"
        scope = "email groups profile openid"
    # -> see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#scopes
    # and https://dexidp.io/docs/custom-scopes-claims-clients/#cross-client-trust-and-authorized-party
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.cluster_issuer }}
        external-dns.alpha.kubernetes.io/managed-by: {{ .Values.external_dns_manager }}
      hosts:
        - {{ .Values.host }}
      tls:
        - hosts:
            - {{ .Values.host }}
          secretName: oauth2-proxy-cert
