apiVersion: v1
kind: Secret
metadata:
  name: admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "admin" "key" "password" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: frappe
spec:
  interval: 1h
  url: https://helm.erpnext.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: erpnext
spec:
  interval: 1h
  chart:
    spec:
      chart: erpnext
      version: "^6"
      sourceRef:
        kind: HelmRepository
        name: frappe
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  valuesFrom:
    - kind: Secret
      name: admin
      valuesKey: password
      targetPath: "jobs.createSite.adminPassword"
  values:
    {{- if .Values.custom_image.enabled }}
    image:
      repository: {{ .Values.custom_image.repository | quote }}
      tag: {{ .Values.custom_image.tag | quote }}
      pullPolicy: {{ .Values.custom_image.pullPolicy }}
    {{- end }}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: {{ .Values.host }}
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: erpnext-tls
        hosts:
           - {{ .Values.host }}
    jobs:
      createSite:
        enabled: true
        siteName: {{ .Values.host }}
        # adminPassword injected via FluxCD
        installApps:
          - erpnext
          {{- if .Values.custom_image.enabled }}
          {{ .Values.custom_image.enable_apps | toYaml | indent 10 }}
          {{- end }}
    persistence:
      worker:
        enabled: true
        storageClass: {{ .Values.storage_class }} # TODO: #56 PR to make this accept null for the default class
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "erpnext-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: erpnext
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "erpnext-mariadb-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: data-erpnext-mariadb-0
