- name: Node group assignment
  hosts: all
  run_once: true
  roles:
    - role: host-grouping

- name: Cluster config
  hosts: all
  run_once: true
  pre_tasks:
    - name: Load cluster config values
      ansible.builtin.include_vars: values.yaml
    - name: Load cluster secrets
      ansible.builtin.include_vars: secrets.yaml
  roles:
    - role: cluster-config

- name: Destroy all nodes
  hosts: all
  become: true
  roles:
    - role: node-destruction
      when: "not cluster.virtual"
      vars:
        control: "{{ inventory_hostname in control_hosts }}"
