apiVersion: v1
kind: Secret
metadata:
  name: loki-basicauth
type: Opaque
data:
  name: {{ "cluster" | b64enc }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "loki-basicauth" "key" "password" "providedValues" (list "") "length" 16 "context" $) }}
---
{{- if not .Values.bootstrap }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "^6.6.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  dependsOn:
    - name: minio
  valuesFrom:
    - kind: Secret
      name: minio-loki
      valuesKey: secret
      targetPath: loki.storage.s3.secretAccessKey
    - kind: Secret
      name: loki-basicauth
      valuesKey: password
      targetPath: gateway.basicAuth.password
  values:
    loki:
      configStorageType: Secret
      storage:
        type: s3
        s3:
          endpoint: http://minio:9000
          accessKeyId: loki
          # secretAccessKey: "" # injected, see above
          s3ForcePathStyle: true
          insecure: true
        bucketNames:
          chunks: chunks
          ruler: ruler
          admin: admin
      compactor:
        retention_enabled: true
        delete_request_store: filesystem
      limits_config:
        retention_period: 168h
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
    chunksCache:
      allocatedMemory: 512
    resultsCache:
      allocatedMemory: 512
    read:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: {{ .Values.ha_deployment.max_replicas }}
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    write:
      replicas: 1
      resources:
        requests:
          cpu: 30m
          memory: 192Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: {{ .Values.ha_deployment.max_replicas }}
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
      persistence:
        size: 4Gi
        storageClass: local
    tableManager:
      resources:
        cpu: 50m
        memory: 64Mi
    backend:
      replicas: 1
      resources:
        requests:
          cpu: 30m
          memory: 64Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: {{ .Values.ha_deployment.max_replicas }}
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
      persistence:
        size: 1Gi
        storageClass: local
    gateway:
      basicAuth:
        enabled: true
        username: cluster
        # password: "" # injected, see above
      replicas: 1
      resources:
        requests:
          cpu: 300m # measured on 2023-11-30
          memory: 32Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: {{ .Values.ha_deployment.max_replicas }}
        targetCPUUtilizationPercentage: 65
        targetMemoryUtilizationPercentage: 65
    lokiCanary:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    test:
      enabled: false
{{- end }}
