apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-telemetry
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
{{- if not .Values.bootstrap }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector-daemon
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-collector
      version: "^0.124.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  values:
    mode: daemonset
    image:
      repository: otel/opentelemetry-collector
    presets:
      kubernetesAttributes:
        enabled: true
      kubeletMetrics:
        enabled: false
      logsCollection:
        enabled: true
    config:
      exporters:
        otlphttp:
          logs_endpoint: http://vlogs:9428/insert/opentelemetry/v1/logs
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
spec:
  interval: 1h
  chart:
    spec:
      chart: opentelemetry-collector
      version: "^0.124.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  timeout: '15m0s' # Account for slow performance of cluster on first setup.
  values:
    mode: deployment
    image:
      repository: otel/opentelemetry-collector
    replicaCount: 1
    presets:
      clusterMetrics:
        enabled: false
      kubernetesEvents:
        enabled: true
    config:
      exporters:
        otlphttp:
          logs_endpoint: http://vlogs:9428/insert/opentelemetry/v1/logs
{{- end }}
