apiVersion: v2
name: upgrade-controller
description: Setup encrypted longhorn storage class
type: application
version: "0.0.1"
appVersion: "0.0.1"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
