host: ""

oidc_client:
  # Only works with keycloak currently.
  idp_url: ""
  id: ""
  secret:
    namespace: null
    name: ""
    key: "secret"

s3:
  endpoint: "" # Domain without protocol of your S3 endpoint (e.g. "s3.example.org")
  region: "eu-central-1" # Required by Longhorn, just leave the default if you don't have zones
  access_key_id: "" # Your S3 access key id
  access_key_secret:
    # Your S3 access key secret
    namespace: null
    name: ""
    key: "secret"
  bucket: "" # Name of bucket

smtp: # For admin notifications
  host: ""
  port: ""
  user: ""
  password_secret:
    namespace: null
    name: ""
    key: "secret"
  from_address: ""

admin_email: ""

admin_group: ""

# Pass public k8s node ips so that k3s metrics endpoints can be monitored (if not vcluster)
node_endpoints: []

cluster_issuer: "acme"
external_dns_manager: "cluster"

letsencrypt_staging: false

bootstrap: false # Set to true to install in bootstrap mode (minimum deployment to support core functions and CRs)
