apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-postgres
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: '^16.7.4'
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-redis
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: '^21.1.5'
---
apiVersion: v1
kind: Secret
metadata:
  name: nocodb-smtp
type: Opaque
data:
  {{- $passRef := .Values.smtp.password_secret }}
  password: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data) $passRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nocodb-postgres
type: Opaque
data:
  user-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb-postgres" "key" "user-password" "providedValues" (list "") "length" 16 "context" $) }}
  postgres-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb-postgres" "key" "postgres-password" "providedValues" (list "") "length" 16 "context" $) }}
  replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb-postgres" "key" "replication-password" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nocodb-redis
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb-postgres" "key" "user-password" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nocodb
type: Opaque
data:
  jwt-secret: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb" "key" "jwt-secret" "providedValues" (list "") "length" 32 "context" $) }}
  admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nocodb" "key" "admin-password" "providedValues" (list "") "length" 20 "context" $) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4Gi"
  storageClassName: ha
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb-postgres
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitnami-postgres
  values:
    global:
      postgresql:
        auth:
          username: nocodb
          database: nocodb
          existingSecret: nocodb-postgres
          secretKeys:
            userPasswordKey: user-password
            adminPasswordKey: postgres-password
            replicationPasswordKey: replication-password
    primary:
      nodeSelector:
        {{- if not (eq .Values.zone "") }}
        topology.kubernetes.io/zone: {{ .Values.zone }}
        {{- else }}
        backbone: "1"
        {{- end }}
      persistence:
        size: 4Gi
        storageClass: ha
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb-redis
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
  values:
    fullnameOverride: nocodb-redis
    architecture: standalone
    auth:
      existingSecret: nocodb-redis
      existingSecretPasswordKey: password
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    master:
      nodeSelector:
        {{- if not (eq .Values.zone "") }}
        topology.kubernetes.io/zone: {{ .Values.zone }}
        {{- else }}
        backbone: "1"
        {{- end }}
      persistence:
        size: 2Gi
        storageClass: local
      resources:
        requests:
          memory: 128Mi
          cpu: 30m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb-urls
spec:
  interval: 1h
  chart:
    spec:
      chart: nocodb-urls
      version: "^0.1.0"
      sourceRef:
        kind: HelmRepository
        name: base-config-repo
        namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb
spec:
  type: ClusterIP
  selector:
    app: nocodb
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
  labels:
    app: nocodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      hostname: nocodb
      nodeSelector:
        {{- if not (eq .Values.zone "") }}
        topology.kubernetes.io/zone: {{ .Values.zone }}
        {{- else }}
        backbone: "1"
        {{- end }}
      containers:
        - name: nocodb
          image: nocodb/nocodb:latest
          imagePullPolicy: Always
          env:
            - name: NC_DB
              valueFrom:
                secretKeyRef:
                  name: nocodb-urls
                  key: postgres
            - name: NC_AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nocodb
                  key: jwt-secret
            - name: NC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nocodb
                  key: admin-password
            - name: NC_SMTP_HOST
              value: {{ .Values.smtp.host }}
            - name: NC_SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: NC_SMTP_USERNAME
              value: {{ .Values.smtp.user }}
            - name: NC_SMTP_FROM
              value: {{ .Values.smtp.from_address }}
            - name: NC_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nocodb-smtp
                  key: password
            - name: NC_SMTP_SECURE
              value: "true"
            - name: NC_SMTP_REJECT_UNAUTHORIZED
              value: "true"
            - name: NC_PUBLIC_URL
              value: {{ printf "https://%s" .Values.host }}
            - name: NC_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: nocodb-urls
                  key: redis
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
          volumeMounts:
            - name: data
              mountPath: "/usr/app/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nocodb-data
{{- if .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: nocodb-cert
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nocodb
                port:
                  name: http
{{- end }}
{{- if .Values.snapshots.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "nocodb-data-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: nocodb-data
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
{{- end }}
