domain: ""
cluster_name: "cluster"

policy: sync # External DNS policy ("upsert-only" or "sync")

# Currently only Digitalocean provider supported.
token_secret:
  namespace: null
  name: ""
  key: "token"
