apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-1
spec:
  interval: 1h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rocketchat
spec:
  interval: 1h
  url: https://rocketchat.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client
type: Opaque
data:
  {{- $secretRef1 := .Values.oidc_client.secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef1.namespace) $secretRef1.name).data) $secretRef1.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp
type: Opaque
data:
  {{- $passRef := .Values.smtp.password_secret }}
  password: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data) $passRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-mongodb
type: Opaque
data:
  mongodb-passwords: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-passwords" "providedValues" (list "") "context" $) }}
  mongodb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-root-password" "providedValues" (list "") "context" $) }}
  mongodb-metrics-password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-metrics-password" "providedValues" (list "") "context" $) }}
  mongodb-replica-set-key: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-replica-set-key" "providedValues" (list "") "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat-mongodb-urls
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/rocketchat-mongodb-urls
      sourceRef:
        kind: GitRepository
        name: base-repo
        namespace: flux-system
      reconcileStrategy: Revision
---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-admin" "key" "password" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat-mongodb
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: '13.16.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami-1
  values:
    nodeSelector:
      {{- if not (eq .Values.zone "") }}
      topology.kubernetes.io/zone: {{ .Values.zone }}
      {{- else }}
      backbone: "1"
      {{- end }}
    auth:
      usernames:
        - rocketchat
      databases:
        - rocketchat
      existingSecret: rocketchat-mongodb
    architecture: replicaset
    replicaCount: 1
    arbiter:
      enabled: false
      pdb:
        minAvailable: 0
    pdb:
      minAvailable: 0
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 1.5Gi
        cpu: 200m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
spec:
  interval: 1h
  chart:
    spec:
      chart: rocketchat
      version: '^6.4.1'
      sourceRef:
        kind: HelmRepository
        name: rocketchat
  dependsOn:
    - name: rocketchat-mongodb-urls
    - name: rocketchat-mongodb
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            {{- if not (eq .Values.zone "") }}
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - {{ .Values.zone }}
            {{- else }}
            - key: backbone
              operator: In
              values:
              - "1"
            {{- end }}
    replicaCount: 2
    minAvailable: 1
    host: {{ .Values.host }}
    ingress:
      enabled: {{ .Values.ingress }}
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      tls:
        - hosts:
            - {{ .Values.host }}
          secretName: rocketchat-tls
    existingMongodbSecret: rc-mongodb-urls
    mongodb:
      enabled: false
    persistence:
      enabled: true
      size: 4Gi
      accessMode: ReadWriteMany
    prometheusScraping:
      enabled: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        memory: 768Mi
        cpu: 200m
    extraEnv:
      - name: Site_Name
        value: {{ printf "%s Chat" .Values.org.name }}

      - name: ADMIN_USERNAME
        value: superadmin
      - name: ADMIN_PASS
        valueFrom:
          secretKeyRef:
            name: rocketchat-admin
            key: password
      - name: ADMIN_EMAIL
        value: {{ .Values.admin_email }}
      
      - name: OVERWRITE_SETTING_Accounts_RegistrationForm
        value: Disabled
      - name: Accounts_RegistrationForm_LinkReplacementText
        value: ""
      - name: OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowEmailChange
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowPasswordChange
        value: "false"
      
      - name: Show_Setup_Wizard
        value: completed

      - name: Accounts_OAuth_Custom_Keycloak
        value: "true"
      - name: Accounts_OAuth_Custom_Keycloak_url
        value: {{ .Values.oidc_client.idp_url }}
      - name: Accounts_OAuth_Custom_Keycloak_token_path
        value: {{ printf "%s/protocol/openid-connect/token" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_identity_path
        value: {{ printf "%s/protocol/openid-connect/userinfo" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_authorize_path
        value: {{ printf "%s/protocol/openid-connect/auth" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_token_sent_via
        value: header
      - name: Accounts_OAuth_Custom_Keycloak_scope
        value: "openid profile groups email"
      - name: Accounts_OAuth_Custom_Keycloak_id
        value: cluster-oidc
      - name: Accounts_OAuth_Custom_Keycloak_secret
        valueFrom:
          secretKeyRef:
            name: oidc-client
            key: secret
      - name: Accounts_OAuth_Custom_Keycloak_login_style
        value: redirect
      - name: Accounts_OAuth_Custom_Keycloak_button_label_text
        value: {{ printf "%s Login / Signup" .Values.org.name | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_key_field
        value: sub
      - name: Accounts_OAuth_Custom_Keycloak_username_field
        value: preferred_username
      - name: Accounts_OAuth_Custom_Keycloak_email_field
        value: email
      - name: Accounts_OAuth_Custom_Keycloak_name_field
        value: name
      - name: Accounts_OAuth_Custom_Keycloak_merge_users
        value: "true"

      - name: OVERWRITE_SETTING_FileUpload_MaxFileSize
        value: "10485760"

      - name: OVERWRITE_SETTING_SMTP_Password
        valueFrom:
          secretKeyRef:
            name: smtp
            key: password

      - name: UI_Use_Real_Name
        value: "true"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rocketchat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rocketchat-rocketchat
  minReplicas: 2
  maxReplicas: {{ .Values.max_replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65
{{- if .Values.snapshots.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "rocketchat-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: rocketchat-rocketchat
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "rocketchat-mongodb-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: datadir-rocketchat-mongodb-0
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
{{- end }}
