apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rocketchat
spec:
  interval: 1h
  url: https://rocketchat.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client
type: Opaque
data:
  {{- $secretRef1 := .Values.oidc_client.secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef1.namespace) $secretRef1.name).data) $secretRef1.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp
type: Opaque
data:
  {{- $passRef := .Values.smtp.password_secret }}
  password: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data) $passRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-mongodb
type: Opaque
data:
  mongodb-passwords: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-passwords" "providedValues" (list "") "context" $) }}
  mongodb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-root-password" "providedValues" (list "") "context" $) }}
  mongodb-metrics-password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-metrics-password" "providedValues" (list "") "context" $) }}
  mongodb-replica-set-key: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-mongodb" "key" "mongodb-replica-set-key" "providedValues" (list "") "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rc-mongodb-urls
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/custom-template
      sourceRef:
        kind: GitRepository
        name: base-repo
        namespace: flux-system
      reconcileStrategy: Revision
  values:
    template: |
      {{ .Files.Get "files/mongodb-urls.yaml" | nindent 6 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-admin" "key" "password" "providedValues" (list "") "length" 16 "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat-mongodb
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: '^6'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    initdbScriptsConfigMap: rocketchat-mongodb-fix-clustermonitor-role-configmap
    auth:
      usernames:
        - rocketchat
      databases:
        - rocketchat
      existingSecret: rocketchat-mongodb
    architecture: replicaset
    replicaCount: 1
    arbiter:
      enabled: false
      pdb:
        minAvailable: 0
    pdb:
      minAvailable: 0
    persistence:
      enabled: true
      size: 4Gi
    volumePermissions: { enabled: true }
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
spec:
  interval: 1h
  chart:
    spec:
      chart: rocketchat
      version: '^6'
      sourceRef:
        kind: HelmRepository
        name: rocketchat
  dependsOn:
    - name: rc-mongodb-urls
    - name: rocketchat-mongodb
  values:
    minAvailable: 1
    host: {{ .Values.host }}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      tls:
        - hosts:
            - {{ .Values.host }}
          secretName: rocketchat-tls
    existingMongodbSecret: rc-mongodb-urls
    mongodb:
      enabled: false
    persistence:
      enabled: true
      size: 4Gi
      accessMode: ReadWriteMany
    prometheusScraping:
      enabled: true
    serviceMonitor:
      enabled: true
    extraEnv:
      - name: Site_Name
        value: {{ printf "%s Chat" .Values.org.name }}

      - name: ADMIN_USERNAME
        value: superadmin
      - name: ADMIN_PASS
        valueFrom:
          secretKeyRef:
            name: rocketchat-admin
            key: password
      - name: ADMIN_EMAIL
        value: {{ .Values.admin_email }}
      
      - name: OVERWRITE_SETTING_Accounts_RegistrationForm
        value: Disabled
      - name: Accounts_RegistrationForm_LinkReplacementText
        value: ""
      - name: OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowEmailChange
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowPasswordChange
        value: "false"
      
      - name: Show_Setup_Wizard
        value: completed

      - name: Accounts_OAuth_Custom_Keycloak
        value: "true"
      - name: Accounts_OAuth_Custom_Keycloak_url
        value: {{ .Values.oidc_client.idp_url }}
      - name: Accounts_OAuth_Custom_Keycloak_token_path
        value: {{ printf "%s/protocol/openid-connect/token" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_identity_path
        value: {{ printf "%s/protocol/openid-connect/userinfo" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_authorize_path
        value: {{ printf "%s/protocol/openid-connect/auth" .Values.oidc_client.idp_url | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_token_sent_via
        value: header
      - name: Accounts_OAuth_Custom_Keycloak_scope
        value: "openid profile groups email"
      - name: Accounts_OAuth_Custom_Keycloak_id
        value: cluster-oidc
      - name: Accounts_OAuth_Custom_Keycloak_secret
        valueFrom:
          secretKeyRef:
            name: oidc-client
            key: secret
      - name: Accounts_OAuth_Custom_Keycloak_login_style
        value: redirect
      - name: Accounts_OAuth_Custom_Keycloak_button_label_text
        value: {{ printf "%s Login / Signup" .Values.org.name | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_key_field
        value: sub
      - name: Accounts_OAuth_Custom_Keycloak_username_field
        value: preferred_username
      - name: Accounts_OAuth_Custom_Keycloak_email_field
        value: email
      - name: Accounts_OAuth_Custom_Keycloak_name_field
        value: name
      - name: Accounts_OAuth_Custom_Keycloak_merge_users
        value: "true"

      - name: OVERWRITE_SETTING_FileUpload_MaxFileSize
        value: "10485760"

      - name: OVERWRITE_SETTING_SMTP_Password
        valueFrom:
          secretKeyRef:
            name: smtp
            key: password

      - name: UI_Use_Real_Name
        value: "true"
