apiVersion: v2
name: mail-stack
description: Mail server + mailing list service + Web UIs
type: application
version: "0.4.1"
appVersion: "0.4.1"

dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
