endpoints:
  # Integers and numeric strings map to exposed node ports,
  # other strings map to subdomains (exposed via ingresses).
  dashboard: null

cluster_name: ""

oauth2_proxy_host: ""

admin_group: ""

vcluster: false
