apiVersion: v1
kind: Secret
metadata:
  name: oidc-client
type: Opaque
data:
  {{- $secretRef1 := .Values.oidc_client.secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef1.namespace) $secretRef1.name).data) $secretRef1.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-access-key
type: Opaque
data:
  {{- $secretRef2 := .Values.s3.access_key_secret }}
  secret: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $secretRef2.namespace) $secretRef2.name).data) $secretRef2.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-mariadb" "key" "mariadb-password" "providedValues" (list "") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-mariadb" "key" "mariadb-root-password" "providedValues" (list "") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-mariadb" "key" "mariadb-replication-password" "providedValues" (list "") "context" $) }}
  mariadb-username: {{ "nextcloud" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
type: Opaque
data:
  nextcloud-username: {{ "admin" | b64enc }}
  nextcloud-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud" "key" "nextcloud-password" "providedValues" (list "") "length" 16 "context" $) }}
  nextcloud-token: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud" "key" "nextcloud-token" "providedValues" (list "") "length" 16 "context" $) }}
  smtp-username: {{ .Values.smtp.user | b64enc }}
  {{- $passRef := .Values.smtp.password_secret }}
  smtp-password: {{ get ((lookup "v1" "Secret" (default .Release.Namespace $passRef.namespace) $passRef.name).data) $passRef.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-redis
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-redis" "key" "password" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: onlyofficejwt
type: Opaque
data:
  JWT_ENABLED: {{ "true" b64enc }}
  JWT_SECRET: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyofficejwt" "key" "JWT_SECRET" "providedValues" (list "") "length" 16 "context" $) }}
  JWT_HEADER: {{ "Authorization" | b64enc }}
  JWT_IN_BODY: {{ "false" | b64enc }}
  JWT_ENABLED_INBOX: {{ "false" | b64enc }}
  JWT_ENABLED_OUTBOX: {{ "false" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-postgres
type: Opaque
data:
  postgres-password: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyoffice-postgres" "key" "postgres-password" "providedValues" (list "") "context" $) }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyoffice-postgres" "key" "password" "providedValues" (list "") "context" $) }}
  replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyoffice-postgres" "key" "replication-password" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-redis
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyoffice-redis" "key" "password" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-rabbitmq
type: Opaque
data:
  rabbitmq-password: {{ include "common.secrets.passwords.manage" (dict "secret" "onlyoffice-rabbitmq" "key" "rabbitmq-password" "providedValues" (list "") "context" $) }}
