{{- $pg_admin_pw := include "common.secrets.passwords.manage" (dict "secret" "postgresql-passwords" "key" "postgres-password" "providedValues" (list "") "context" $) -}}
{{- $pg_user_pw := include "common.secrets.passwords.manage" (dict "secret" "postgresql-passwords" "key" "password" "providedValues" (list "") "context" $) -}}
{{- $pg_repl_pw := include "common.secrets.passwords.manage" (dict "secret" "postgresql-passwords" "key" "replication-password" "providedValues" (list "") "context" $) -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-passwords
type: Opaque
data:
  postgres-password: {{ $pg_admin_pw }}
  password: {{ $pg_user_pw }}
  replication-password: {{ $pg_repl_pw }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hyperkitty-key
type: Opaque
data:
  api-key: {{ include "common.secrets.passwords.manage" (dict "secret" "hyperkitty-key" "key" "api-key" "providedValues" (list "") "context" $) }}
---
{{ $mailman_admin_pw := include "common.secrets.passwords.manage" (dict "secret" "mailman-admin" "key" "password" "providedValues" (list "") "context" $) -}}
{{ $mailman_admin_auth := printf "restadmin:%s" $mailman_admin_pw | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: mailman-admin
type: Opaque
data:
  password: {{ $mailman_admin_pw }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 60m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '^12'
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    auth:
      username: mailman
      database: mailman
      existingSecret: postgresql-passwords
---
apiVersion: v1
kind: Service
metadata:
  name: mailman-core
spec:
  type: ClusterIP
  selector:
    app: mailman-core
  ports:
    - port: 80
      targetPort: api
      name: api
    - port: 8024
      targetPort: lmtp
      name: lmtp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailman-core
  labels:
    app: mailman-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailman-core
  template:
    metadata:
      labels:
        app: mailman-core
    spec:
      hostname: mailman-core
      containers:
        - name: mailman-core
          image: maxking/mailman-core:0.4
          env:
            - name: DATABASE_URL
              value: {{ printf "postgresql://mailman:%s@postgresql/mailman" (b64dec $pg_user_pw) }}
            - name: DATABASE_TYPE
              value: postgres
            - name: DATABASE_CLASS
              value: "mailman.database.postgresql.PostgreSQLDatabase"
            - name: HYPERKITTY_URL
              value: "http://mailman-web/hyperkitty"
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperkitty-key
                  key: api-key
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-admin
                  key: password
            - name: MTA
              value: "postfix"
            - name: SMTP_HOST
              value: mailu-front
          ports:
            - name: api
              containerPort: 8001
            - name: lmtp
              containerPort: 8024
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 15
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 1
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: "/opt/mailman/"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailman-core-data
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" "django-secret" "key" "secret" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailman-web-config
data:
  settings_local.py: |
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "SERVERS": [
                {
                    "id": "local-sso",  # 30 characters or less
                    "name": {{ printf "%s SSO" .Values.org.name | quote }},
                    "server_url": {{ .Values.oidcClient.idpURL | quote }},
                    "APP": {
                        "client_id": {{ .Values.oidcClient.id | quote }},
                        "secret": {{ .Values.oidcClient.secret | quote }},
                    },
                },
            ]
        }
    }
    import sys
    # Configure verbose logging to stdout.
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
                'level': 'INFO',
                'stream': sys.stdout,
            }
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
            'postorius': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True
            },
        },
        'formatters': {
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(process)d %(name)s %(message)s'
            }
        }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailman-web-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mailman-web
spec:
  type: ClusterIP
  selector:
    app: mailman-web
  ports:
    - port: 80
      targetPort: ui
      name: ui
    - port: 8080
      targetPort: uwsgi
      name: uwsgi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailman-web
  labels:
    app: mailman-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailman-web
  template:
    metadata:
      labels:
        app: mailman-web
    spec:
      hostname: mailman-web
      initContainers:
        - name: copy
          image: busybox:1
          command: ["/bin/sh", "-c", "cp /opt/mailman-web-config/* /opt/mailman-web-data"]
          volumeMounts:
            - mountPath: "/opt/mailman-web-config"
              name: config
            - mountPath: "/opt/mailman-web-data"
              name: data
      containers:
        - name: mailman-web
          image: maxking/mailman-web:0.4
          env:
            - name: SERVE_FROM_DOMAIN
              value: {{ .Values.domains.mailman }}
            - name: DATABASE_URL
              value: {{ printf "postgresql://mailman:%s@postgresql/mailman" (b64dec $pg_user_pw) }}
            - name: DATABASE_TYPE
              value: "postgres"
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hyperkitty-key
                  key: api-key
            - name: MAILMAN_REST_URL
              value: "http://mailman-core"
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-admin
                  key: password
            - name: MAILMAN_HOSTNAME
              value: mailman-core
            - name: MAILMAN_ADMIN_USER
              value: {{ .Values.admin.user }}
            - name: MAILMAN_ADMIN_EMAIL
              value: {{ .Values.admin.email }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret
            - name: SMTP_HOST
              value: mailu-front
            - name: SMTP_HOST_USER
              value: {{ printf "admin@%s" .Values.mailDomain }}
            - name: SMTP_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailu-admin
                  key: password
          ports:
            - name: ui
              containerPort: 8000
            - name: uwsgi
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: ui
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 15
          readinessProbe:
            tcpSocket:
              port: ui
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 1
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: "/opt/mailman-web-data"
              name: data
      volumes:
        - name: config
          configMap:
            name: mailman-web-config
        - name: data
          persistentVolumeClaim:
            claimName: mailman-web-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailman
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.domains.mailman }}
      secretName: mailman-cert
  rules:
    - host: {{ .Values.domains.mailman }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailman-web
                port:
                  name: ui
