apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailman-core-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
{{- if .Values.snapshots.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailman-core-data-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailman-core-data
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
{{- end }}
