apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mailu
spec:
  interval: 1h
  url: https://mailu.github.io/helm-charts/
---
{{- if not .Values.ingress }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailu-selfsigned-tls
spec:
  secretName: mailu-selfsigned-tls
  dnsNames:
    - {{ .Values.hosts.mailu }}
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
spec:
  interval: 1h
  chart:
    spec:
      chart: mailu
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: mailu
  timeout: 10m
  values:
    domain: {{ .Values.domain }}
    hostnames:
      - {{ .Values.hosts.mailu }}
    initialAccount:
      enabled: true
      domain: {{ .Values.domain }}
      username: admin
      existingSecret: mailu-admin
      existingSecretPasswordKey: password
    customization:
      siteName: {{ printf "%s Mail" .Values.org.name }}
      logoUrl: {{ .Values.org.logo_url | quote }}
    subnet: "10.0.0.0/8" # Cluster network. Make sure to set your NetworkPolicies straight!
    logLevel: INFO
    persistence:
      single_pvc: false
    ingress:
      enabled: {{ .Values.ingress }}
      {{- if not .Values.ingress }}
      existingSecret: mailu-selfsigned-tls
      {{- end }}
      annotations:
        nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-User, X-Auth-Request-Groups, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Access-Token"
        nginx.ingress.kubernetes.io/auth-signin: {{ printf "https://%s/oauth2/start?rd=$scheme%%3A%%2F%%2F$host$escaped_request_uri" .Values.oauth2_proxy_host }}
        nginx.ingress.kubernetes.io/auth-url: {{ printf "https://%s/oauth2/auth" .Values.oauth2_proxy_host }}
        kubernetes.io/tls-acme: "true"
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 4Gi
    redis:
      master:
        persistence:
          size: 2Gi
    front:
      kind: DaemonSet
      hostPort:
        enabled: false
      externalService:
        enabled: true
        type: NodePort
        externalTrafficPolicy: Local
      {{- if .Values.use_mailu_proxy_auth }}
      extraEnvVars:
        - name: PROXY_AUTH_WHITELIST
          value: "10.0.0.0/8"
        - name: PROXY_AUTH_HEADER
          value: "X-Auth-Request-Email"
        - name: PROXY_AUTH_CREATE
          value: "True"
      {{- end }}
    postfix:
      {{ if .Values.require_ptr -}}
      nodeSelector:
        PTR: {{ .Values.hosts.mailu }}
      {{ end -}}
      persistence:
        size: 2Gi
        claimNameOverride: mailu-postfix
      extraVolumes:
        - name: mailman
          persistentVolumeClaim:
            claimName: mailman-core-data
      extraVolumeMounts:
        - name: mailman
          mountPath: /mailman
      overrides:
        postfix.cf: |
          # Support the default VERP delimiter.
          recipient_delimiter = +
          unknown_local_recipient_reject_code = 550
          owner_request_special = no
          
          transport_maps = regexp:/mailman/var/data/postfix_lmtp
          local_recipient_maps = regexp:/mailman/var/data/postfix_lmtp
          relay_domains = regexp:/mailman/var/data/postfix_domains
    admin:
      persistence:
        size: 2Gi
        claimNameOverride: mailu-admin
      {{- if .Values.use_mailu_proxy_auth }}
      extraEnvVars:
        - name: PROXY_AUTH_WHITELIST
          value: "10.0.0.0/8"
        - name: PROXY_AUTH_HEADER
          value: "X-Auth-Request-Email"
        - name: PROXY_AUTH_CREATE
          value: "True"
      {{- end }}
    dovecot:
      persistence:
        size: 4Gi
        claimNameOverride: mailu-dovecot
    webmail:
      persistence:
        size: 2Gi
        claimNameOverride: mailu-webmail
      {{- if .Values.use_mailu_proxy_auth }}
      extraEnvVars:
        - name: PROXY_AUTH_WHITELIST
          value: "10.0.0.0/8"
        - name: PROXY_AUTH_HEADER
          value: "X-Auth-Request-Email"
        - name: PROXY_AUTH_CREATE
          value: "True"
      {{- end }}
    fetchmail:
      enabled: true
      persistence:
        size: 2Gi
        claimNameOverride: mailu-fetchmail
    webdav:
      enabled: true
      persistence:
        size: 2Gi
        claimNameOverride: mailu-webdav
{{- if .Values.snapshots.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-postfix-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-postfix
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-admin-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-admin
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-dovecot-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-dovecot
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-webmail-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-webmail
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-fetchmail-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-fetchmail
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-webdav-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: mailu-webdav
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "mailu-mariadb-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: data-mailu-mariadb-0
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
{{- end }}
