apiVersion: v1
kind: ConfigMap
metadata:
  name: mailu-postfix-overrides
  labels:
    app.kubernetes.io/name: mailu
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/component: postfix
data:
  postfix.cf: |
    my_variable = my_value
    # Support the default VERP delimiter.
    recipient_delimiter = +
    unknown_local_recipient_reject_code = 550
    owner_request_special = no
    
    transport_maps =
        regexp:/mailman/var/data/postfix_lmtp
    local_recipient_maps =
        regexp:/mailman/var/data/postfix_lmtp
    relay_domains =
        regexp:/mailman/var/data/postfix_domains
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mailu
spec:
  interval: 60m
  url: https://mailu.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
spec:
  interval: 10m
  chart:
    spec:
      chart: mailu
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: mailu
  timeout: 10m
  values:
    domain: {{ .Values.domain }}
    hostnames:
      - {{ .Values.hosts.mailu }}
    initialAccount:
      enabled: true
      domain: {{ .Values.domain }}
      username: admin
      existingSecret: mailu-admin
      existingSecretPasswordKey: password
    customization:
      siteName: {{ printf "%s Mail" .Values.org.name }}
      logoUrl: {{ .Values.org.logoURL | quote }}
    subnet: "10.0.0.0/8" # Cluster network. Make sure to set your NetworkPolicies straight!
    logLevel: INFO
    persistence:
      single_pvc: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
        {{ include "proxy_auth_annotations" . | nindent 8 }}
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
    front:
      hostPort:
        enabled: false
      externalService:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
      extraEnvVars:
        - name: PROXY_AUTH_WHITELIST
          value: "10.0.0.0/8"
        - name: PROXY_AUTH_HEADER
          value: "X-Auth-Request-Email"
        - name: PROXY_AUTH_CREATE
          value: "True"
    postfix:
      extraVolumes:
        - name: mailman
          persistentVolumeClaim:
            claimName: mailman-core-data
        - name: overrides
          configMap:
            name: mailu-postfix-overrides
      extraVolumeMounts:
        - name: mailman
          mountPath: /mailman
        - name: overrides
          mountPath: /overrides
      persistence:
        size: 5Gi
      # Currently broken in upstream chart.
      # Move ConfigMap from above in here once this is fixed: 
      # overrides: {}
    admin:
      persistence:
        size: 5Gi
    dovecot:
      persistence:
        size: 5Gi
    webmail:
      persistence:
        size: 5Gi
    # Currently broken in upstream chart. 
    # Uncomment once this is closed: https://github.com/Mailu/helm-charts/issues/231
    # fetchmail:
    #   enabled: true
      # persistence:
      #   size: 5Gi
    # Currently broken in upstream chart. 
    # Uncomment once this is closed: https://github.com/Mailu/helm-charts/issues/232
    # webdav:
    #   enabled: true
      # persistence:
      #   size: 5Gi
