host: ""

admin_email: ""

smtp: # For notifications
  host: ""
  port: ""
  user: ""
  password_secret:
    namespace: kube-system
    name: mail-smtp
    key: password
  from_address: ""

ingress: true

snapshots:
  enabled: true
  class_name: snap

zone: ""

redis:
  enabled: false # redis currently causes nocodb to crash without error logs...
