apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sso-clients
spec:
  interval: 1h
  chart:
    spec:
      chart: sso-clients
      version: "^0.1.4"
      sourceRef:
        kind: HelmRepository
        name: base-config-repo
        namespace: flux-system
  values:
    oidc:
      id: nextcloud
      redirect_uris:
        - {{ printf "https://%s/apps/oidc_login/oidc" .Values.hosts.nextcloud }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nextcloud-autoconfig
data:
  setup.sh: |
    #!/bin/bash

    if [ -f ~/autoconf-running ]
    then
      echo "Autoconfig script is already running. Exiting."
      exit 0
    fi

    touch ~/autoconf-running
    trap 'rm ~/autoconf-running' EXIT

    until [[ $(runuser --user www-data -- /var/www/html/occ status 2> /dev/null | grep "installed:") =~ "true" ]]; do
      echo 'waiting for nextcloud to start...'
      sleep 5
    done
    echo 'nextcloud is up.'

    echo 'installing apps...'
    for APP in $(cat apps.txt); do
      if ! [[ -d /var/www/html/custom_apps/$APP || -d /var/www/html/apps/$APP ]] ; then
        echo "installing $APP"
        runuser --user www-data -- /var/www/html/occ app:install $APP
      fi
    done
    echo 'installing apps... done'

    echo 'loading config.json...'
    ( echo "cat <<EOF" ; cat config.json ; echo EOF ) | sh > /var/www/html/config.json
    runuser --user www-data -- /var/www/html/occ config:import config.json
    rm /var/www/html/config.json
    echo 'loading config.json... done'

    echo 'nextcloud all set up.'
  apps.txt: | 
    oidc_login
    {{- if .Values.onlyoffice.enabled }}
    onlyoffice
    {{- end }}
  config.json: |
    {
      "system": {},
      "apps": {
        {{- if .Values.onlyoffice.enabled }}
        "onlyoffice": {
          "DocumentServerUrl": {{ printf "https://%s" .Values.hosts.onlyoffice | quote }},
          "jwt_secret": "$OO_JWT_SECRET"
        },
        {{- end }}
        "files": {
          "default_quota": "1 GB"
        }
      }
    }
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-nextcloud
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
    {{- if not .Values.storage.auto_backup }}
    velero.io/exclude-from-backup: "true"
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
    recurring-job.longhorn.io/snapshot-daily: enabled
    {{- end }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ not (eq .Values.zone "") | ternary (printf "ha-zone-%s" .Values.zone) "ha-backbone" }}{{ .Values.storage.encrypted | ternary "-enc" "" }}
  volumeMode: Filesystem
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: '6.6.2'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  timeout: 20m0s
  values:
    # TODO: #55 Deploy multiple nextcloud replicas with RollingUpdate and RWX volume once upstream NFS issue is solved
    # Upstream issue: <https://github.com/nextcloud/helm/issues/399>
    # replicaCount: 2
    resources:
      requests:
        cpu: 150m # measured on 2024-08-24
        memory: 1Gi # measured on 2024-08-24
    ingress:
      enabled: {{ .Values.ingress }}
      tls:
        - secretName: nextcloud-tls
          hosts:
            - {{ .Values.hosts.nextcloud }}
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/server-snippet: |-
          location = /.well-known/webdav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
    nextcloud:
      # strategy:
      #   type: RollingUpdate
      #   rollingUpdate:
      #     maxSurge: 1
      #     maxUnavailable: 1
      host: {{ .Values.hosts.nextcloud }}
      existingSecret:
        enabled: true
        secretName: nextcloud
      mail:
        enabled: true
        fromAddress: {{ index (.Values.smtp.from_address | splitList "@") 0 }}
        domain: {{ index (.Values.smtp.from_address | splitList "@") 1 }}
        smtp:
          port: {{ .Values.smtp.port }}
          secure: ssl
      extraEnv:
        - name: OIDC_IDP_URL
          valueFrom:
            configMapKeyRef:
              name: sso-keycloak
              key: url
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-client.nextcloud
              key: secret
        {{- if .Values.onlyoffice.enabled }}
        - name: OO_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: onlyofficejwt
              key: JWT_SECRET
        {{- end }}
      phpConfigs:
        opcache-recommended.ini: |
          opcache.enable=1
          opcache.interned_strings_buffer=64
          opcache.max_accelerated_files=10000
          opcache.memory_consumption=256
          opcache.save_comments=1
          opcache.revalidate_freq=60
          opcache.jit=1255
          opcache.jit_buffer_size=256M
      configs:
        logging.config.php: |
          <?php
          $CONFIG = array (
            "log_type" => "file",
            "logfile" => "data/nextcloud.log",
            "loglevel" => {{ .Values.debug | ternary 0 2 }},
          );
          ?>
        oidc.config.php: | 
          <?php
          $CONFIG = array (
            // See here for explanation: https://github.com/pulsejet/nextcloud-oidc-login#config
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_provider_url' => getenv('OIDC_IDP_URL'),
            'oidc_login_client_id' => 'nextcloud',
            'oidc_login_client_secret' => getenv('OIDC_CLIENT_SECRET'),
            'oidc_login_auto_redirect' => {{ .Values.oidc.auto_redirect }},
            'oidc_login_logout_url' => {{ printf "https://%s" .Values.hosts.nextcloud | quote }},
            'oidc_login_end_session_redirect' => false,
            'oidc_login_button_text' => {{ printf "%s Login / Signup" .Values.org.name | quote }},
            'oidc_login_hide_password_form' => false,
            'oidc_login_use_id_token' => false,
            'oidc_login_attributes' => array (
                'id' => 'preferred_username',
                'name' => 'given_name',
                'mail' => 'email',
                'quota' => 'nextcloudQuota',
                'home' => 'homeDirectory',
                {{- if .Values.oidc.map_groups }}
                'groups' => 'groups',
                {{- end }}
                'photoURL' => 'picture',
                'is_admin' => 'is_admin',
            ),
            'oidc_login_use_external_storage' => false,
            'oidc_login_scope' => 'openid profile groups email is_admin',
            'oidc_login_proxy_ldap' => false,
            'oidc_login_disable_registration' => false,
            'oidc_login_redir_fallback' => true,
            'oidc_login_tls_verify' => true,
          );
          ?>
        locale.config.php: | 
          <?php
          $CONFIG = array (
            'default_locale' => {{ .Values.org.default_locale | quote }},
            'default_phone_region' => {{ not (eq .Values.org.default_phone_region "") | ternary .Values.org.default_phone_region (index (.Values.org.default_locale | splitList "_") 1 | upper) | quote }}
          );
          ?>
        proxy.config.php: | 
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.42.0.0/16',
              2 => '::1',
              3 => '2001:cafe:42:0::/56'
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'overwriteprotocol' => 'https',
          );
          ?>
        mail.config.php: | 
          <?php
          $CONFIG = array (
            'mail_smtptimeout' => 30,
          );
          ?>
        maintenance.config.php: |
          <?php
          $CONFIG = array (
            // Start maintenance at 2am, after all backups should have completed.
            'maintenance_window_start' => 2,
          );
          ?>
      {{- if .Values.s3.enabled }}
      objectStore:
        s3:
          enabled: true
          region: {{ .Values.s3.region }}
          autoCreate: true
          existingSecret: s3-storage
          secretKeys:
            host: host
            accessKey: id
            secretKey: secret
            bucket: bucket
            sse_c_key: sse_c_key
      {{- end }}
      extraSidecarContainers:
        - name: nextcloud-logger
          image: busybox
          command: [/bin/sh, -c, 'while ! test -f "/var/www/html/data/nextcloud.log"; do sleep 1; done; tail -n 0 -f /var/www/html/data/nextcloud.log']
          volumeMounts:
          - name: nextcloud-main
            mountPath: /var/www/html/data
            subPath: data
      {{- if .Values.autoconfig.enabled }}
      extraVolumes:
        - name: autoconfig
          configMap:
            name: nextcloud-autoconfig
      extraVolumeMounts:
        - name: autoconfig
          mountPath: /autoconfig
          readOnly: true
      hooks:
        post-installation: |
          cd /autoconfig
          bash setup.sh
        post-upgrade: |
          cd /autoconfig
          bash setup.sh
      {{- end }}
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      existingSecret:
        enabled: true
        secretName: nextcloud-mariadb
        usernameKey: mariadb-username
        passwordKey: mariadb-password
    cronjob:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud-nextcloud
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 30m # measured on 2023-11-30
          memory: 32Mi # measured on 2023-11-30
    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: nextcloud-redis
        existingSecretPasswordKey: password
      master:
        persistence:
          size: 3Gi # measured on 2024-02-26
          storageClass: local
        resources:
          requests:
            memory: 128Mi # measured on 2023-11-30
            cpu: 50m # measured on 2023-11-30
        nodeSelector:
          {{- if not (eq .Values.zone "") }}
          topology.kubernetes.io/zone: {{ .Values.zone }}
          {{- else }}
          backbone: "1"
          {{- end }}
      architecture: standalone
    mariadb:
      enabled: true
      auth:
        existingSecret: nextcloud-mariadb
      global:
        storageClass: {{ (eq .Values.zone "") | ternary "ha-backbone" (printf "ha-zone-%s" .Values.zone) }}
      primary:
        persistence:
          enabled: true
          size: 4Gi
        resources:
          requests:
            cpu: 100m # measured on 2024-08-24
            memory: 512Mi # measured on 2024-08-24
    {{- if not (eq .Values.zone "") }}
        nodeSelector:
          topology.kubernetes.io/zone: {{ .Values.zone }}
    nodeSelector:
      topology.kubernetes.io/zone: {{ .Values.zone }}
    {{- else }}
        nodeSelector:
          backbone: "1"
    nodeSelector:
      backbone: "1"
    {{- end }}

{{- if .Values.snapshots.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "nextcloud-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: nextcloud-nextcloud
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ printf "nextcloud-mariadb-%s" (now | date "20060102150405") }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  source:
    persistentVolumeClaimName: data-nextcloud-mariadb-0
  {{- if .Values.snapshots.class_name }}
  volumeSnapshotClassName: {{ .Values.snapshots.class_name }}
  {{- end }}
{{- end }}
