{% if not cluster.components.tailscale.enabled %}
flannel-backend: "wireguard-native"
flannel-external-ip: True
{% endif %}
flannel-ipv6-masq: True # Needed to fix IPv6 egress issue: https://github.com/k3s-io/k3s/issues/5766#issuecomment-1352575431
cluster-cidr: "10.42.0.0/16,2001:cafe:42:0::/56"
service-cidr: "10.43.0.0/16,2001:cafe:42:1::/112"
disable:
  - traefik
  - local-storage
etcd-expose-metrics: true
secrets-encryption: true
kube-apiserver-arg:
  - "oidc-issuer-url=https://{{ cluster.components.sso.endpoints.keycloak }}.{{ cluster.domain }}/realms/master"
  - "oidc-client-id=cluster-oidc"
  - "oidc-groups-claim=groups"
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
  - "horizontal-pod-autoscaler-tolerance=0.3"
kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
tls-san: "{{ cluster.components.k8s.endpoints.api }}.{{ cluster.domain }}"
kubelet-arg+:
  - "kube-reserved=cpu=1.8,memory=2.6Gi,ephemeral-storage=8Gi"
