- name: Check whether host is already known
  loop: "{{ groups['all'] }}"
  ansible.builtin.command: "ssh-keygen -F {{ hostvars[item].inventory_hostname }}"
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: known_hosts_check

- name: Generate new lines for known_hosts
  loop: "{{ known_hosts_check.results }}"
  when: "item.rc != 0"
  ansible.builtin.command: "ssh-keyscan -H {{ hostvars[item.item].inventory_hostname }}"
  register: known_hosts_entries
  changed_when: true

- name: Add lines to known_hosts
  loop: "{{ known_hosts_entries.results }}"
  when: "item.stdout is defined"
  ansible.builtin.lineinfile:
    dest: ~/.ssh/known_hosts
    line: "{{ item.stdout }}"
    insertafter: EOF
    mode: '0644'
