apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
# Taken from: https://github.com/fluxcd/flux2/tree/main/manifests/monitoring/monitoring-config
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
      relabelings:
        # https://github.com/prometheus-operator/prometheus-operator/issues/4816
        - sourceLabels: [__meta_kubernetes_pod_phase]
          action: keep
          regex: Running
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: grafana
  namespace: o11y-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  type: grafana
  address: "http://kube-prometheus-stack-grafana.o11y-system/api/annotations"
  secretRef:
    name: grafana-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  namespace: flux-system
type: Opaque
data:
  issuerURL: {{ printf "https://%s" (include "get_hostname" (dict "service" "dex" "context" $)) | b64enc }}
  clientID: {{ "admin-oidc" | b64enc }}
  clientSecret: {{ .Values.clusterSecret | b64enc }}
  redirectURL: {{ printf "https://%s/oauth2/callback" (include "get_hostname" (dict "service" "weave_gitops" "context" $)) | b64enc }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  interval: 1h
  timeout: '30m0s' # Setting up public domains for OIDC takes time.
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        external-dns.alpha.kubernetes.io/managed-by: {{ include "cluster_fqn" . }}
      hosts:
        - host: {{ include "get_hostname" (dict "service" "weave_gitops" "context" $) }}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - {{ include "get_hostname" (dict "service" "weave_gitops" "context" $) }}
    metrics:
      enabled: false
    adminUser:
      create: true
      username: admin
      passwordHash: {{ htpasswd "admin" .Values.clusterSecret }}
    # resources: 
    #   limits:
    #     memory: 256Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: flux-system
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob "config/grafana-dashboards/flux*").AsConfig | indent 2 }}
