apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "^4"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    {{ .Files.Get "bootstrap-values/ingress-nginx.yaml" | nindent 4 }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ingress-system
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "^6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    sources:
      - service
      - ingress
    txtOwnerId: {{ include "cluster_fqn" . | quote }}
    {{- .Values.external_dns | toYaml | nindent 4 }}
    serviceMonitor:
      enabled: true
    # resources: 
    #   limits:
    #     memory: 256Mi
    annotationFilter: {{ printf "external-dns.alpha.kubernetes.io/managed-by in (%s)" (include "cluster_fqn" .) | quote }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
spec:
  acme:
    email: {{ .Values.admin.email | quote }}
    {{ if .Values.letsencrypt_staging -}}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else -}}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: acme-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: ingress-system
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob "config/grafana-dashboards/nginx*").AsConfig | indent 2 }}
