apiVersion: v1
kind: Namespace
metadata:
  name: o11y-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: o11y-system
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ .Values.clusterSecret | b64enc | quote }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: o11y-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "^45"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    prometheusOperator:
      admissionWebhooks:
        timeoutSeconds: 30 # Prevent timeouts during helm upgrade
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 8Gi
        retention: 7d
    grafana:
      admin:
        existingSecret: grafana-admin
        userKey: username
        passwordKey: password
      grafana.ini:
        server:
          root_url: {{ printf "https://%s" (include "get_hostname" (dict "service" "grafana" "context" $)) }}
        smtp: 
          enabled: true
          {{ .Values.smtp | toYaml | nindent 10 }}
        auth:
          oauth_auto_login: true
          disable_login_form: true
        auth.generic_oauth:
          # See: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/
          enabled: true
          name: Admin OIDC
          client_id: admin-oidc
          client_secret: {{ .Values.clusterSecret | quote }}
          scopes: openid,profile,email,groups
          auth_url: {{ printf "https://%s/auth" (include "get_hostname" (dict "service" "dex" "context" $)) | quote }}
          token_url: {{ printf "https://%s/token" (include "get_hostname" (dict "service" "dex" "context" $)) | quote }}
          api_url: {{ printf "https://%s/userinfo" (include "get_hostname" (dict "service" "dex" "context" $)) | quote }}
          allow_sign_up: true
          allowed_groups: {{ .Values.admin.group | quote }}
          role_attribute_path: "contains(groups[*], {{ .Values.admin.group | squote }}) && 'Admin' || 'Viewer'"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: acme
          external-dns.alpha.kubernetes.io/managed-by: {{ include "cluster_fqn" . }}
        hosts:
          - {{ include "get_hostname" (dict "service" "grafana" "context" $) }}
        tls:
          - hosts:
              - {{ include "get_hostname" (dict "service" "grafana" "context" $) }}
            secretName: grafana-cert
      persistence:
        enabled: true
      alerting:
        rules.yaml:
          apiVersion: 1
          groups:
            - orgId: 1
              name: default
              folder: default
              interval: 60s
              rules:
                - uid: flux-reconcile-fail
                  title: Flux Reconcile Fail
                  condition: C
                  data:
                    - refId: A
                      queryType: ''
                      relativeTimeRange:
                        from: 600
                        to: 0
                      datasourceUid: prometheus
                      model:
                        editorMode: builder
                        expr: max by(exported_namespace, name, kind) (gotk_reconcile_condition{type="Ready",
                          status="False"})
                        hide: false
                        intervalMs: 1000
                        legendFormat: __auto
                        maxDataPoints: 43200
                        range: true
                        refId: A
                    - refId: B
                      queryType: ''
                      relativeTimeRange:
                        from: 0
                        to: 0
                      datasourceUid: __expr__
                      model:
                        conditions:
                        - evaluator:
                            params:
                            - 0
                            - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                        datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                        expression: A
                        intervalMs: 1000
                        maxDataPoints: 43200
                        reducer: max
                        refId: B
                        type: reduce
                    - refId: C
                      queryType: ''
                      relativeTimeRange:
                        from: 0
                        to: 0
                      datasourceUid: __expr__
                      model:
                        conditions:
                        - evaluator:
                            params:
                            - 0
                            - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                        datasource:
                          name: Expression
                          type: __expr__
                          uid: __expr__
                        expression: B
                        intervalMs: 1000
                        maxDataPoints: 43200
                        refId: C
                        type: threshold
                  dashboardUid: flux-cluster
                  panelId: 28
                  noDataState: NoData
                  for: 600s
                  annotations:
                    runbook_url: "https://fluxcd.io/flux/cheatsheets/troubleshooting/"
                  labels:
                    severity: critical
        contactpoints.yaml:
          apiVersion: 1
          contactPoints:
            - orgId: 1
              name: default
              receivers:
                - uid: default-email-receiver
                  type: email
                  settings:
                    addresses: {{ .Values.admin.email }}
                    singleEmail: true
    alertmanager:
      enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: o11y-system
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "^2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  timeout: '10m0s' # Account for slow performance of cluster on first setup.
  values:
    loki:
      isDefault: false
      config:
        schema_config:
          configs:
          - from: "2022-12-30"
            store: boltdb-shipper
            object_store: s3
            schema: v11
            index:
              prefix: index_
              period: 24h
        ruler:
          storage:
            type: local
            local:
              directory: /tmp/rules
          rule_path: /tmp/scratch
          alertmanager_url: http://kube-prometheus-stack-alertmanager.o11y-system:9093
          ring:
            kvstore:
              store: inmemory
          enable_api: true
        storage_config:
          aws:
            # https://grafana.com/docs/loki/latest/configuration/#s3_storage_config
            s3: {{ printf "https://%s" .Values.s3.endpoint }}
            bucketnames: {{ .Values.s3.buckets.loki }}
            endpoint: {{ .Values.s3.endpoint }}
            region: {{ .Values.s3.region }}
            access_key_id: {{ .Values.s3.access_key.id | quote }}
            secret_access_key: {{ .Values.s3.access_key.secret | quote }}
        limits_config:
          retention_period: 168h
