apiVersion: v2
name: host-cluster-infra
description: Infrastructure chart to supply baseline k8s infrastructure
type: application
version: "0.0.1"
appVersion: "0.0.1"
dependencies:
  - name: common
    version: "^1"
    repository: https://charts.bitnami.com/bitnami
  - name: longhorn
    version: "^1"
    repository: https://charts.longhorn.io
    condition: bootstrap
  - name: longhorn
    version: "^6"
    repository: https://piraeus.io/helm-charts/
    condition: bootstrap
