apiVersion: v2
name: storage-stack
description: Longhorn-based storage system
type: application
version: "0.2.0"
appVersion: "0.2.0"
dependencies:
- name: common
  version: "^1"
  repository: https://charts.bitnami.com/bitnami
