apiVersion: v2
name: storage
description: Longhorn-based storage system
type: application
version: "0.2.1"
appVersion: "0.2.1"
dependencies:
- name: common
  version: "^1"
  repository: https://charts.bitnami.com/bitnami
