apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-snapshot-class
spec:
  interval: 1h
  chart:
    spec:
      chart: default-snapshot-class
      version: "^0.1.0"
      sourceRef:
        kind: HelmRepository
        name: base-config-repo
        namespace: flux-system
  dependsOn:
    - name: snapshot-controller
