{{- if not .Values.vcluster }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: piraeus
spec:
  interval: 1h
  url: https://piraeus.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-controller
      version: "^2.2.0"
      sourceRef:
        kind: HelmRepository
        name: piraeus
{{- end }}
