- name: Chart details
  ansible.builtin.debug:
    msg: "Deploying chart {{ chart.name }} into namespace {{ chart.namespace }}"

- name: Ensure chart namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ chart.namespace }}"
  register: k8s_result
  retries: 6 # K8s API tends to be unavailable at times during setup.
  delay: 20
  until: "k8s_result is not failed"

- name: Ensure HelmRelease for chart exists
  vars:
    default_vars:
      bootstrap: false
      vcluster: "{{ cluster.virtual }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: "{{ chart.name }}"
        namespace: "{{ chart.namespace }}"
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/{{ chart.name }}"
            sourceRef:
              kind: GitRepository
              name: base-repo
              namespace: flux-system
            reconcileStrategy: Revision
        values: "{{ chart.chart_values | default({}) | combine(default_vars) }}"
  register: k8s_result
  retries: 6 # K8s API tends to be unavailable at times during setup.
  delay: 20
  until: "k8s_result is not failed"

- name: Reconcile HelmRelease
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ansible.builtin.command:
    argv:
      - flux
      - reconcile
      - hr
      - "{{ chart.name }}"
      - "-n={{ chart.namespace }}"
  changed_when: true
  register: k8s_result
  retries: 6 # K8s API tends to be unavailable at times during setup.
  delay: 20
  until: "k8s_result is not failed"
