- name: Bootstrap host-cluster infrastructure
  when: "not vcluster"
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
  loop:
    - name: storage-stack
      namespace: longhorn-system

- name: Setup vcluster
  when: "vcluster"
  block:
    - name: Create vcluster for domain
      kubernetes.core.helm:
        wait: true
        name: "{{ cluster_fqn }}"
        release_namespace: "{{ cluster_fqn }}"
        chart_repo_url: https://charts.loft.sh
        chart_ref: vcluster
        chart_version: "^0.15"
        values:
          sync:
            persistentvolumes:
              enabled: true
            storageclasses:
              enabled: true
            volumesnapshots:
              enabled: true
            nodes:
              enabled: true
              enableScheduler: true
              nodeSelector: "{{ cluster_fqn }}=1"
          isolation:
            enabled: true
          proxy:
            metricsServer:
              nodes:
                enabled: true
              pods:
                enabled: true

    - name: Switch kubecontext to vcluster
      ansible.builtin.command: "vcluster connect {{ cluster_fqn }}"
      changed_when: true

- name: Bootstrap cluster infrastructure
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
  loop:
    - name: cert-stack
      namespace: cert-system
    - name: ingress-stack
      namespace: ingress-system
    - name: telemetry-stack
      namespace: telemetry-system
    - name: cicd-stack
      namespace: flux-system

- name: Ensure all required secrets exist
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: kube-system
      type: Opaque
      data:
        secret: "{{ vars[item.inventoryKey] | b64encode }}"
  loop:
    - inventoryKey: adminIDPClientSecret
      name: admin-idp-client
    - inventoryKey: smtpPassword
      name: smtp
    - inventoryKey: s3AccessKeySecret
      name: s3
    - inventoryKey: externalDNSToken
      name: external-dns

- name: Ensure base GitRepository exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: base-repo
        namespace: flux-system
      spec:
        interval: 1h
        url: "{{ baseRepo }}"
        ref:
          branch: "{{ baseBranch }}"

- name: Reconcile base git repo
  ansible.builtin.command: "flux reconcile source git base-repo -n flux-system"
  changed_when: true

- name: Ensure HelmReleases for host-cluster infrastructure exist
  when: "not vcluster"
  ansible.builtin.include_tasks:
    file: deploy-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
  loop:
    - name: upgrade-controller
      namespace: kube-system
      values: {}

    - name: storage-stack
      namespace: longhorn-system
      values:
        host: "{{ subdomains.storage }}.{{ domain }}"
        oauth2ProxyHost: "{{ subdomains.auth }}.{{ domain }}"
        adminGroup: "{{ adminGroup }}"
        s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.backup}) }}"

    - name: backup-stack
      namespace: backup-system
      values:
        s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.backup}) }}"

- name: Apply backup restoration
  when: "restoreFromBackup"
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: velero.io/v1
      kind: Restore
      metadata:
        name: initial-cluster-restore
        namespace: backup-system
      spec:
        backupName: "{{ restoreFromBackup }}"

- name: Ensure HelmReleases for cluster infrastructure exist
  ansible.builtin.include_tasks:
    file: deploy-chart.yaml
    apply:
      vars:
        chart: "{{ item }}"
  loop:
    - name: admin-rbac
      namespace: kube-system
      values:
        adminGroup: "{{ adminGroup }}"

    - name: crypto-storage
      namespace: longhorn-system
      values:
        cluster_fqn: "{{ cluster_fqn }}"

    - name: cert-stack
      namespace: cert-system
      values: {}

    - name: ingress-stack
      namespace: ingress-system
      values:
        domain: "{{ domain }}"
        clusterName: "{{ clusterName }}"
        externalDNS:
          tokenSecret:
            namespace: kube-system
            name: external-dns
            key: secret

    - name: sso-stack
      namespace: sso-system
      values:
        domain: "{{ domain }}"
        org: "{{ org }}"
        hosts:
          keycloak: "{{ subdomains.idp }}.{{ domain }}"
          dex: "{{ subdomains.oidc }}.{{ domain }}"
        clients:
          oidc:
            - id: cluster-oidc
              redirectURIs:
                - "https://{{ subdomains.auth }}.{{ domain }}/oauth2/callback"
                - "http://localhost:8000/"
                - "https://*.{{ domain }}/*"
        smtp: "{{ smtp | combine({'passwordSecret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"
        adminIDP: "{{ adminIDP | combine({'clientSecret': {'name': 'admin-idp-client', 'namespace': 'kube-system', 'key': 'secret'}}) }}"

    - name: authproxy
      namespace: sso-system
      values:
        domain: "{{ domain }}"
        org: "{{ org }}"
        host: "{{ subdomains.auth }}.{{ domain }}"
        oidcClient:
          idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
          id: "cluster-oidc"
          secret:
            name: "oidc-client.cluster-oidc"
            key: secret

    - name: telemetry-stack
      namespace: telemetry-system
      values:
        domain: "{{ domain }}"
        org: "{{ org }}"
        host: "{{ subdomains.telemetry }}.{{ domain }}"
        oidcClient:
          idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
          id: "cluster-oidc"
          secret:
            name: "oidc-client.cluster-oidc"
            key: secret
        adminEmail: "{{ adminEmail }}"
        adminGroup: "{{ adminGroup }}"
        s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.logs}) }}"
        smtp: "{{ smtp | combine({'passwordSecret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"

    - name: cicd-stack
      namespace: flux-system
      values:
        host: "{{ subdomains.gitops }}.{{ domain }}"
        oidcClient:
          idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
          id: "cluster-oidc"
          secret:
            name: "oidc-client.cluster-oidc"
            key: secret

    - name: k8s-dashboard
      namespace: kube-system
      values:
        host: "{{ subdomains.control }}.{{ domain }}"
        oauth2ProxyHost: "{{ subdomains.auth }}.{{ domain }}"
        adminGroup: "{{ adminGroup }}"
