- name: Bootstrap host-cluster infrastructure
  when: "not vcluster"
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        item: "{{ item }}"
  with_items:
    - chart: storage-stack
      namespace: longhorn-system

- name: Setup vcluster
  when: "vcluster"
  block:
    - name: Create vcluster for domain
      kubernetes.core.helm:
        wait: true
        name: "{{ cluster_fqn }}"
        release_namespace: "{{ cluster_fqn }}"
        chart_repo_url: https://charts.loft.sh
        chart_ref: vcluster
        chart_version: "^0.15"
        values:
          sync:
            persistentvolumes:
              enabled: true
            storageclasses:
              enabled: true
            volumesnapshots:
              enabled: true
            nodes:
              enabled: true
              enableScheduler: true
              nodeSelector: "{{ cluster_fqn }}=1"
          isolation:
            enabled: true
          proxy:
            metricsServer:
              nodes:
                enabled: true
              pods:
                enabled: true

    - name: Switch kubecontext to vcluster
      ansible.builtin.command: "vcluster connect {{ cluster_fqn }}"
      register: kubectx_switch
      changed_when: true

- name: Bootstrap cluster infrastructure
  ansible.builtin.include_tasks:
    file: bootstrap-chart.yaml
    apply:
      vars:
        item: "{{ item }}"
  with_items:
    - chart: cert-manager
      namespace: kube-system
    - chart: ingress-stack
      namespace: ingress-system
    - chart: telemetry-stack
      namespace: telemetry-system
    - chart: cicd-stack
      namespace: flux-system

- name: Ensure base GitRepository exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: base-repo
        namespace: flux-system
      spec:
        interval: 1h
        url: "{{ baseRepo }}"
        ref:
          branch: "{{ baseBranch }}"

- name: Ensure all required secrets exist
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: kube-system
      type: Opaque
      data:
        secret: "{{ vars[item.inventoryKey] }}"
  with_items:
    - inventoryKey: adminIDPClientSecret
      name: admin-idp-client
    - inventoryKey: smtpPassword
      name: smtp
    - inventoryKey: s3AccessKeySecret
      name: s3
    - inventoryKey: externalDNSToken
      name: external-dns

- name: Ensure HelmRelease for storage-stack exists
  when: "not vcluster"
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: storage-stack
        namespace: longhorn-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/storage-stack"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          host: "{{ subdomains.storage }}.{{ domain }}"
          oauth2ProxyHost: "{{ subdomains.auth }}.{{ domain }}"
          adminGroup: "{{ adminGroup }}"
          s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.backup}) }}"

- name: Ensure backup-system exists
  when: "not vcluster"
  block:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "backup-system"

    - name: Deploy backup-stack
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: backup-stack
            namespace: backup-system
          spec:
            interval: 1h
            chart:
              spec:
                chart: "./charts/backup-stack"
                sourceRef:
                  kind: GitRepository
                  name: base-repo
                reconcileStrategy: Revision
            values:
              s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.backup}) }}"

    - name: Apply backup restoration
      when: "restoreFromBackup is defined"
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: velero.io/v1
          kind: Restore
          metadata:
            name: initial-cluster-restore
            namespace: backup-system
          spec:
            backupName: "{{ restoreFromBackup }}"

- name: Ensure HelmRelease for upgrade-controller exists
  when: "not vcluster"
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: upgrade-controller
        namespace: kube-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/upgrade-controller"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision

- name: Ensure HelmRelease for admin RBAC exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: admin-rbac
        namespace: kube-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/admin-rbac"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          adminGroup: "{{ adminGroup }}"

- name: Ensure HelmRelease for encrypted storage class exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: crypto-storage
        namespace: longhorn-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/crypto-storage"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          cluster_fqn: "{{ cluster_fqn }}"

- name: Ensure HelmRelease for cert-manager exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: cert-manager
        namespace: kube-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/cert-manager"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision

- name: Ensure HelmRelease for ingress-stack exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: ingress-stack
        namespace: ingress-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/ingress-stack"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          domain: "{{ domain }}"
          clusterName: "{{ clusterName }}"
          externalDNS: "{{ externalDNS | combine({'tokenSecret': {'name': 'external-dns', 'namespace': 'kube-system', 'key': 'secret'}}) }}"

- name: Ensure sso-system exists
  block:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "sso-system"

    - name: Deploy sso-stack
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: sso-stack
            namespace: sso-system
          spec:
            interval: 1h
            chart:
              spec:
                chart: "./charts/sso-stack"
                sourceRef:
                  kind: GitRepository
                  name: base-repo
                reconcileStrategy: Revision
            values:
              domain: "{{ domain }}"
              org: "{{ org }}"
              hosts:
                keycloak: "{{ subdomains.idp }}.{{ domain }}"
                dex: "{{ subdomains.oidc }}.{{ domain }}"
              clients:
                oidc:
                  - id: cluster-oidc
                    redirectURIs:
                      - "https://{{ subdomains.auth }}.{{ domain }}/oauth2/callback"
                      - "http://localhost:8000/"
                      - "https://*.{{ domain }}/*"
              smtp: "{{ smtp | combine({'passwordSecret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"
              adminIDP: "{{ adminIDP | combine({'clientSecret': {'name': 'admin-idp-client', 'namespace': 'kube-system', 'key': 'secret'}}) }}"

    - name: Deploy authproxy
      kubernetes.core.k8s:
        wait: true
        definition:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: authproxy
            namespace: sso-system
          spec:
            interval: 1h
            chart:
              spec:
                chart: "./charts/authproxy"
                sourceRef:
                  kind: GitRepository
                  name: base-repo
                reconcileStrategy: Revision
            values:
              domain: "{{ domain }}"
              org: "{{ org }}"
              host: "{{ subdomains.auth }}.{{ domain }}"
              oidcClient:
                idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
                id: "cluster-oidc"
                secret:
                  name: "oidc-client.cluster-oidc"
                  key: secret

- name: Ensure HelmRelease for telemetry-stack exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: telemetry-stack
        namespace: telemetry-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/telemetry-stack"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          domain: "{{ domain }}"
          org: "{{ org }}"
          host: "{{ subdomains.telemetry }}.{{ domain }}"
          oidcClient:
            idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
            id: "cluster-oidc"
            secret:
              name: "oidc-client.cluster-oidc"
              key: secret
          adminEmail: "{{ adminEmail }}"
          adminGroup: "{{ adminGroup }}"
          s3: "{{ s3 | combine({'accessKeySecret': {'name': 's3', 'namespace': 'kube-system', 'key': 'secret'}, 'bucket': s3Buckets.logs}) }}"
          smtp: "{{ smtp | combine({'passwordSecret': {'name': 'smtp', 'namespace': 'kube-system', 'key': 'secret'}}) }}"

- name: Ensure HelmRelease for cicd-stack exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: cicd-stack
        namespace: flux-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/cicd-stack"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          host: "{{ subdomains.gitops }}.{{ domain }}"
          oidcClient:
            idpURL: "https://{{ subdomains.idp }}.{{ domain }}/realms/main"
            id: "cluster-oidc"
            secret:
              name: "oidc-client.cluster-oidc"
              key: secret

- name: Ensure HelmRelease for k8s-dashboard exists
  kubernetes.core.k8s:
    wait: true
    definition:
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: k8s-dashboard
        namespace: kube-system
      spec:
        interval: 1h
        chart:
          spec:
            chart: "./charts/k8s-dashboard"
            sourceRef:
              kind: GitRepository
              name: base-repo
            reconcileStrategy: Revision
        values:
          host: "{{ subdomains.control }}.{{ domain }}"
          oauth2ProxyHost: "{{ subdomains.auth }}.{{ domain }}"
          adminGroup: "{{ adminGroup }}"
