# Cluster secrets template.
cluster_secrets:
  # Naming of dns secret key(s) depends on chosen provider and can be looked up in 
  # external-dns chart values: https://artifacthub.io/packages/helm/bitnami/external-dns?modal=values
  # Look for `<provider name>.secretName` setting.
  # Note that not all providers support reading credentials from a secret. 
  # If yours does not, you'll have to pass the creds via `dns.extra_config`.
  dns: {}
  mail-smtp:
    password: ""
  backup-s3:
    access_key_secret: ""

  # Required if tailscale is enabled.
  tailscale:
    auth_key: ""
